<?php

/**
 * @file
 * Module hooks for MyEventLane Refunds.
 */

declare(strict_types=1);

/**
 * Implements hook_theme().
 */
function myeventlane_refunds_theme($existing, $type, $theme, $path): array {
  return [
    'myeventlane_refunds_order_list' => [
      'variables' => [
        'orders' => [],
        'event' => NULL,
      ],
      'template' => 'myeventlane-refunds-order-list',
    ],
  ];
}
