<?php

declare(strict_types=1);

namespace Drupal\myeventlane_surface;

/**
 * Single canonical catalogue of MEL experience continuity contracts.
 */
final class MelExperienceRegistry {

  /**
   * @return array<string, \Drupal\myeventlane_surface\ExperienceDefinition>
   */
  public function all(): array {
    return [
      // --- Auth continuity ----------------------------------------------------
      'login_resume' => new ExperienceDefinition(
        id: 'login_resume',
        category: MelExperienceContractCategory::AuthContinuity,
        surfaceOwnership: [MelSurfaceId::Auth->value],
        linkedWorkflowIds: ['first_login'],
        continuityTriggerSignalsAll: [],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['route.auth_login'],
        continuityPriority: 70,
        retentionTier: MelRetentionTier::None,
        retentionImplications: 'None — transactional auth surface only.',
        ctaSequencingNotes: 'Defer browsing CTAs until authentication succeeds; single primary action.',
        accessibilityNotes: 'Expose validation via form errors; avoid duplicate status banners.',
        privacyBoundaries: 'No cross-account hints; session-bound auth context only.',
        crossSurfaceTransitions: ['auth_to_customer'],
        activationExactRoutes: ['user.login'],
      ),
      'onboarding_resume' => new ExperienceDefinition(
        id: 'onboarding_resume',
        category: MelExperienceContractCategory::AuthContinuity,
        surfaceOwnership: [MelSurfaceId::Auth->value, MelSurfaceId::Vendor->value],
        linkedWorkflowIds: ['vendor_profile_completed', 'stripe_connected', 'first_event_created'],
        continuityTriggerSignalsAll: ['vendor.guidance.needs_resume'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['vendor.guidance.needs_resume'],
        continuityPriority: 96,
        retentionTier: MelRetentionTier::Low,
        retentionImplications: 'Vendor may see a single guided resume entry — delegate copy to OnboardingManager routes.',
        ctaSequencingNotes: 'Resume/setup CTAs outrank discovery and analytics prompts.',
        accessibilityNotes: 'Landmark the guided panel; keyboard order matches visual priority.',
        privacyBoundaries: 'Vendor-scoped; never surface another vendor’s onboarding state.',
        crossSurfaceTransitions: ['auth_to_vendor', 'vendor_onboarding_to_shell'],
        activationRoutePrefixes: ['myeventlane_vendor.onboard'],
        activationPathPrefixes: ['/vendor/onboard', '/vendor/dashboard'],
        requireAuthentication: TRUE,
      ),
      'interrupted_checkout_resume' => new ExperienceDefinition(
        id: 'interrupted_checkout_resume',
        category: MelExperienceContractCategory::AuthContinuity,
        surfaceOwnership: [
          MelSurfaceId::Auth->value,
          MelSurfaceId::Customer->value,
          MelSurfaceId::Public->value,
        ],
        linkedWorkflowIds: ['checkout_started', 'ticket_selected', 'attendee_info_complete'],
        continuityTriggerSignalsAll: [],
        continuityTriggerSignalsAny: ['route.checkout_sensitive', 'route.commerce_checkout'],
        resumeGateSignalsAll: ['route.checkout_sensitive'],
        continuityPriority: 94,
        retentionTier: MelRetentionTier::Low,
        retentionImplications: 'Offer calm resume towards cart/checkout — no cross-account cart leakage.',
        ctaSequencingNotes: 'Checkout resume beats promotional continuity; suppress competing surfaces inside checkout panes.',
        accessibilityNotes: 'Checkout trust contexts defer modal focus takeover per MELInteractionSystem.',
        privacyBoundaries: 'Cart/checkout identifiers remain Commerce-scoped and permissioned.',
        crossSurfaceTransitions: ['auth_to_checkout', 'customer_shell_to_checkout'],
        activationRoutePrefixes: ['commerce_cart', 'commerce_checkout'],
        activationPathPrefixes: ['/cart', '/checkout'],
        activateUnderCheckoutSensitiveSurface: TRUE,
      ),
      'password_recovery_return' => new ExperienceDefinition(
        id: 'password_recovery_return',
        category: MelExperienceContractCategory::AuthContinuity,
        surfaceOwnership: [MelSurfaceId::Auth->value, MelSurfaceId::Public->value],
        linkedWorkflowIds: ['first_login'],
        continuityTriggerSignalsAll: [],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: [],
        continuityPriority: 68,
        retentionTier: MelRetentionTier::None,
        retentionImplications: 'None beyond assisting return to login.',
        ctaSequencingNotes: 'Password reset success should route back to login without competing CTAs.',
        accessibilityNotes: 'Announce emailed instructions with polite live regions when used.',
        privacyBoundaries: 'Do not expose whether an email exists in public copy — follow core/user patterns.',
        crossSurfaceTransitions: ['auth_to_auth'],
        activationPathPrefixes: ['/user/password', '/user/reset'],
      ),

      // --- Customer journeys --------------------------------------------------
      'rsvp_completion_calendar_prompt' => new ExperienceDefinition(
        id: 'rsvp_completion_calendar_prompt',
        category: MelExperienceContractCategory::CustomerJourney,
        surfaceOwnership: [MelSurfaceId::Customer->value, MelSurfaceId::Public->value],
        linkedWorkflowIds: ['first_rsvp', 'calendar_connected'],
        continuityTriggerSignalsAll: ['route.rsvp_thankyou'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['route.rsvp_thankyou'],
        continuityPriority: 62,
        retentionTier: MelRetentionTier::Low,
        retentionImplications: 'Optional calendar export prompt — suppress if already connected.',
        ctaSequencingNotes: 'Calendar CTA follows RSVP confirmation; secondary to ticket access when applicable.',
        accessibilityNotes: 'Treat confirmation as polite status; calendar links need descriptive text.',
        privacyBoundaries: 'RSVP identifiers remain event-scoped and permissioned.',
        crossSurfaceTransitions: ['public_to_customer_shell'],
        activationRoutePrefixes: ['myeventlane_rsvp.'],
      ),
      'ticket_purchase_wallet_calendar_share' => new ExperienceDefinition(
        id: 'ticket_purchase_wallet_calendar_share',
        category: MelExperienceContractCategory::CustomerJourney,
        surfaceOwnership: [MelSurfaceId::Customer->value],
        linkedWorkflowIds: ['order_confirmed', 'calendar_prompt', 'social_share_prompt'],
        continuityTriggerSignalsAll: ['route.order_detail'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['route.order_detail'],
        continuityPriority: 88,
        retentionTier: MelRetentionTier::Low,
        retentionImplications: 'Post-order prompts stay on confirmation surfaces only.',
        ctaSequencingNotes: 'Wallet/tickets primary; calendar/share secondary; one primary action per band.',
        accessibilityNotes: 'Avoid stacking multiple primary buttons in the same landmark.',
        privacyBoundaries: 'Order summaries must not expose other purchasers’ data.',
        crossSurfaceTransitions: ['checkout_to_tickets'],
        activationExactRoutes: ['myeventlane_checkout_flow.order_detail'],
        requireAuthentication: TRUE,
      ),
      'saved_event_return_discovery' => new ExperienceDefinition(
        id: 'saved_event_return_discovery',
        category: MelExperienceContractCategory::CustomerJourney,
        surfaceOwnership: [MelSurfaceId::Customer->value],
        linkedWorkflowIds: ['first_saved_event'],
        continuityTriggerSignalsAll: [],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: [],
        continuityPriority: 44,
        retentionTier: MelRetentionTier::Medium,
        retentionImplications: 'Encourage return from saved lists without nagging on unrelated routes.',
        ctaSequencingNotes: 'Discovery CTA secondary when onboarding resume or checkout resume is active.',
        accessibilityNotes: 'Saved lists need meaningful headings and empty-state guidance.',
        privacyBoundaries: 'Saved events are user-private; never hint other accounts’ saves.',
        crossSurfaceTransitions: ['customer_shell_loop'],
        activationExactRoutes: ['myeventlane_dashboard.customer'],
        activationPathPrefixes: ['/my-events'],
        requireAuthentication: TRUE,
      ),
      'support_resolution_followup' => new ExperienceDefinition(
        id: 'support_resolution_followup',
        category: MelExperienceContractCategory::CustomerJourney,
        surfaceOwnership: [
          MelSurfaceId::Customer->value,
          MelSurfaceId::Vendor->value,
          MelSurfaceId::Public->value,
        ],
        linkedWorkflowIds: ['support_contact_started', 'issue_resolved'],
        continuityTriggerSignalsAll: ['support.flags.resolved'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['support.flags.resolved'],
        continuityPriority: 36,
        retentionTier: MelRetentionTier::Low,
        retentionImplications: 'Light re-engagement after resolution — cooldown via owning messaging modules.',
        ctaSequencingNotes: 'Resolution acknowledgement before broader discovery prompts.',
        accessibilityNotes: 'Closure messaging uses polite status semantics.',
        privacyBoundaries: 'Do not expose ticket internals or escalation IDs in customer shells.',
        crossSurfaceTransitions: ['support_to_resolution', 'resolution_to_reengagement'],
        activationPathPrefixes: ['/help'],
        activationRoutePrefixes: ['myeventlane_help_centre.'],
      ),

      // --- Vendor journeys ----------------------------------------------------
      'vendor_onboarding_continuation' => new ExperienceDefinition(
        id: 'vendor_onboarding_continuation',
        category: MelExperienceContractCategory::VendorJourney,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        linkedWorkflowIds: ['vendor_profile_completed', 'vendor_account_created'],
        continuityTriggerSignalsAll: ['vendor.guidance.needs_resume'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['vendor.guidance.needs_resume'],
        continuityPriority: 97,
        retentionTier: MelRetentionTier::Medium,
        retentionImplications: 'Single guided resume via onboarding delegate — no duplicate reminders elsewhere.',
        ctaSequencingNotes: 'Onboarding continuation supersedes analytics and boost prompts.',
        accessibilityNotes: 'Maintain landmark order consistent with vendor shell navigation.',
        privacyBoundaries: 'Vendor isolation enforced server-side; continuity hints never cross vendors.',
        crossSurfaceTransitions: ['vendor_onboarding_to_shell'],
        activationPathPrefixes: ['/vendor/onboard'],
        requireAuthentication: TRUE,
      ),
      'vendor_stripe_continuation' => new ExperienceDefinition(
        id: 'vendor_stripe_continuation',
        category: MelExperienceContractCategory::VendorJourney,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        linkedWorkflowIds: ['stripe_connected'],
        continuityTriggerSignalsAll: ['vendor.guidance.needs_resume'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['vendor.guidance.needs_resume'],
        continuityPriority: 95,
        retentionTier: MelRetentionTier::Low,
        retentionImplications: 'Stripe completion messaging stays operational, not promotional.',
        ctaSequencingNotes: 'Stripe completion outranks analytics CTAs when readiness demands it.',
        accessibilityNotes: 'Treat hosted redirects as focus continuity on return — avoid duplicate banners.',
        privacyBoundaries: 'No Stripe account identifiers in public HTML; follow existing Connect controllers.',
        crossSurfaceTransitions: ['vendor_to_stripe_hosted'],
        activationPathPrefixes: ['/vendor/onboard/stripe', '/vendor/stripe', '/stripe/connect'],
        requireAuthentication: TRUE,
      ),
      'vendor_event_draft_continuation' => new ExperienceDefinition(
        id: 'vendor_event_draft_continuation',
        category: MelExperienceContractCategory::VendorJourney,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        linkedWorkflowIds: ['first_event_created', 'first_event_published'],
        continuityTriggerSignalsAll: ['vendor.guidance.needs_resume'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['vendor.flags.has_events'],
        continuityPriority: 82,
        retentionTier: MelRetentionTier::Medium,
        retentionImplications: 'Nudge draft completion only when vendor already owns draft signals.',
        ctaSequencingNotes: 'Publishing readiness after Stripe/event prerequisites per entity access.',
        accessibilityNotes: 'Studio surfaces remain authoritative for errors.',
        privacyBoundaries: 'Draft continuity never references other vendors’ events.',
        crossSurfaceTransitions: ['vendor_shell_to_studio'],
        activationRoutePrefixes: ['myeventlane_event_studio.'],
        activationPathPrefixes: ['/vendor/events'],
        requireAuthentication: TRUE,
      ),
      'vendor_publish_continuation' => new ExperienceDefinition(
        id: 'vendor_publish_continuation',
        category: MelExperienceContractCategory::VendorJourney,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        linkedWorkflowIds: ['first_event_published'],
        continuityTriggerSignalsAll: [],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['vendor.flags.has_events'],
        continuityPriority: 79,
        retentionTier: MelRetentionTier::Low,
        retentionImplications: 'Post-publish attendee guidance after moderation clears.',
        ctaSequencingNotes: 'Publish continuity yields to moderation deferral from MELStateSystem.',
        accessibilityNotes: 'When moderation hold defers workflow primary, suppress duplicate publish prompts.',
        privacyBoundaries: 'Publishing gates remain access-controlled and moderated.',
        crossSurfaceTransitions: ['vendor_publish_to_attendees'],
        activationPathPrefixes: ['/vendor/events'],
        requireAuthentication: TRUE,
      ),
      'vendor_attendee_management_continuation' => new ExperienceDefinition(
        id: 'vendor_attendee_management_continuation',
        category: MelExperienceContractCategory::VendorJourney,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        linkedWorkflowIds: ['attendees_managed', 'first_ticket_sold'],
        continuityTriggerSignalsAll: ['vendor.surface.active'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['vendor.flags.has_tickets'],
        continuityPriority: 73,
        retentionTier: MelRetentionTier::Low,
        retentionImplications: 'Operational attendee tools — no bulk outreach from continuity layer.',
        ctaSequencingNotes: 'Attendee tools follow publish/ticket milestones.',
        accessibilityNotes: 'Tables and KPI regions require captions or aria-labels via data presentation layer.',
        privacyBoundaries: 'Attendee PII remains permission-scoped.',
        crossSurfaceTransitions: ['vendor_analytics_to_attendees'],
        activationRoutePrefixes: ['myeventlane_rsvp.vendor_', 'myeventlane_checkout_flow.vendor_'],
        activationPathPrefixes: ['/vendor/events'],
        requireAuthentication: TRUE,
      ),
      'vendor_analytics_continuation' => new ExperienceDefinition(
        id: 'vendor_analytics_continuation',
        category: MelExperienceContractCategory::VendorJourney,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        linkedWorkflowIds: ['boost_offer_presented'],
        continuityTriggerSignalsAll: ['vendor.surface.active'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: [],
        continuityPriority: 54,
        retentionTier: MelRetentionTier::None,
        retentionImplications: 'Analytics/boost prompts stay secondary to readiness resumes.',
        ctaSequencingNotes: 'Defer analytics CTAs when Stripe or onboarding resume is active.',
        accessibilityNotes: 'Analytics frames expose summaries without motion-only cues.',
        privacyBoundaries: 'Aggregates only in vendor-authorised contexts.',
        crossSurfaceTransitions: ['vendor_shell_to_analytics'],
        activationPathPrefixes: ['/vendor/analytics', '/vendor/onboard/boost'],
        requireAuthentication: TRUE,
      ),

      // --- Checkout continuity -----------------------------------------------
      'abandoned_checkout_recovery' => new ExperienceDefinition(
        id: 'abandoned_checkout_recovery',
        category: MelExperienceContractCategory::CheckoutContinuity,
        surfaceOwnership: [MelSurfaceId::Customer->value, MelSurfaceId::Public->value],
        linkedWorkflowIds: ['ticket_selected', 'checkout_started'],
        continuityTriggerSignalsAll: [],
        continuityTriggerSignalsAny: ['route.checkout_sensitive'],
        resumeGateSignalsAll: ['route.commerce_checkout'],
        continuityPriority: 91,
        retentionTier: MelRetentionTier::Medium,
        retentionImplications: 'Cart recovery belongs to Commerce + messaging schedulers — continuity supplies sequencing hints only.',
        ctaSequencingNotes: 'Never stack resume banners with checkout panes; honour checkout-sensitive suppression.',
        accessibilityNotes: 'Cart summaries remain readable at 200% zoom.',
        privacyBoundaries: 'Cart ownership enforced by Commerce — no cross-account hints.',
        crossSurfaceTransitions: ['customer_shell_to_checkout'],
        activationRoutePrefixes: ['commerce_cart'],
        activationPathPrefixes: ['/cart'],
        activateUnderCheckoutSensitiveSurface: TRUE,
      ),
      'attendee_info_continuation' => new ExperienceDefinition(
        id: 'attendee_info_continuation',
        category: MelExperienceContractCategory::CheckoutContinuity,
        surfaceOwnership: [MelSurfaceId::Customer->value, MelSurfaceId::Public->value],
        linkedWorkflowIds: ['attendee_info_complete'],
        continuityTriggerSignalsAll: ['route.commerce_checkout'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['route.commerce_checkout'],
        continuityPriority: 86,
        retentionTier: MelRetentionTier::None,
        retentionImplications: 'Pane-level validation stays with Commerce forms.',
        ctaSequencingNotes: 'Single operational focus inside checkout journey.',
        accessibilityNotes: 'Do not replace Commerce field errors with surface banners.',
        privacyBoundaries: 'Attendee fields stay within order scope.',
        crossSurfaceTransitions: ['checkout_step_progress'],
        activationRoutePrefixes: ['commerce_checkout'],
        activationPathPrefixes: ['/checkout'],
        activateUnderCheckoutSensitiveSurface: TRUE,
      ),
      'payment_completion_continuity' => new ExperienceDefinition(
        id: 'payment_completion_continuity',
        category: MelExperienceContractCategory::CheckoutContinuity,
        surfaceOwnership: [MelSurfaceId::Customer->value, MelSurfaceId::Public->value],
        linkedWorkflowIds: ['payment_complete'],
        continuityTriggerSignalsAll: ['route.commerce_checkout'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['route.commerce_checkout'],
        continuityPriority: 93,
        retentionTier: MelRetentionTier::None,
        retentionImplications: 'Payment processing untouched — defer UI to Commerce and trust interactions.',
        ctaSequencingNotes: 'Suppress competing CTAs during processing per state interpretation.',
        accessibilityNotes: 'Processing states use polite or assertive regions as existing interactions define.',
        privacyBoundaries: 'No payment instrument details in continuity payloads.',
        crossSurfaceTransitions: ['checkout_to_confirmation'],
        activationRoutePrefixes: ['commerce_checkout'],
        activationPathPrefixes: ['/checkout'],
        activateUnderCheckoutSensitiveSurface: TRUE,
      ),
      'order_confirmation_continuation' => new ExperienceDefinition(
        id: 'order_confirmation_continuation',
        category: MelExperienceContractCategory::CheckoutContinuity,
        surfaceOwnership: [MelSurfaceId::Customer->value],
        linkedWorkflowIds: ['order_confirmed'],
        continuityTriggerSignalsAll: ['route.order_detail'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['route.order_detail'],
        continuityPriority: 90,
        retentionTier: MelRetentionTier::Low,
        retentionImplications: 'Confirmation continuity encourages tickets/calendar without duplication.',
        ctaSequencingNotes: 'Align with calendar_prompt and social_share_prompt workflow priorities.',
        accessibilityNotes: 'Confirmation headings precede secondary actions.',
        privacyBoundaries: 'Order detail access remains permissioned.',
        crossSurfaceTransitions: ['checkout_to_tickets'],
        activationExactRoutes: ['myeventlane_checkout_flow.order_detail'],
        requireAuthentication: TRUE,
      ),

      // --- Escalation continuity (privacy-safe, signal-driven) --------------
      'moderation_interruption' => new ExperienceDefinition(
        id: 'moderation_interruption',
        category: MelExperienceContractCategory::EscalationContinuity,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        linkedWorkflowIds: ['first_event_published'],
        continuityTriggerSignalsAll: ['event.lifecycle.moderation_hold'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['event.lifecycle.moderation_hold'],
        continuityPriority: 99,
        retentionTier: MelRetentionTier::None,
        retentionImplications: 'Operational pause messaging only — no moderation internals.',
        ctaSequencingNotes: 'Suppress publish/analytics CTAs when moderation deferral active.',
        accessibilityNotes: 'Use warning semantics sparingly; pair with readable explanations.',
        privacyBoundaries: 'Never expose moderator notes, scores, or queues in customer/vendor shells.',
        crossSurfaceTransitions: ['vendor_publish_pause'],
        activationPathPrefixes: ['/vendor/events'],
        requireAuthentication: TRUE,
      ),
      'support_escalation' => new ExperienceDefinition(
        id: 'support_escalation',
        category: MelExperienceContractCategory::EscalationContinuity,
        surfaceOwnership: [MelSurfaceId::Vendor->value, MelSurfaceId::Staff->value],
        linkedWorkflowIds: ['escalation_detected'],
        continuityTriggerSignalsAll: ['support.flags.escalation'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['support.flags.escalation'],
        continuityPriority: 92,
        retentionTier: MelRetentionTier::None,
        retentionImplications: 'Escalation awareness without ticket payload exposure.',
        ctaSequencingNotes: 'Escalation handling precedes growth CTAs.',
        accessibilityNotes: 'Escalation banners follow interaction contracts for assertive delivery.',
        privacyBoundaries: 'Do not expose escalation graphs cross-account.',
        crossSurfaceTransitions: ['support_escalation_loop'],
        requireAuthentication: TRUE,
      ),
      'payout_review' => new ExperienceDefinition(
        id: 'payout_review',
        category: MelExperienceContractCategory::EscalationContinuity,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        linkedWorkflowIds: ['stripe_connected'],
        continuityTriggerSignalsAll: ['vendor.surface.active'],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: [],
        continuityPriority: 87,
        retentionTier: MelRetentionTier::Low,
        retentionImplications: 'Vendor-facing payout readiness hints link to existing Stripe dashboards only.',
        ctaSequencingNotes: 'Operational payout prompts secondary to live checkout-sensitive contexts.',
        accessibilityNotes: 'Link text must describe destination (e.g., Stripe dashboard).',
        privacyBoundaries: 'Banking and capability detail stays in Stripe-hosted surfaces.',
        crossSurfaceTransitions: ['vendor_to_payout_tools'],
        activationPathPrefixes: ['/vendor/stripe', '/vendor/payouts'],
        requireAuthentication: TRUE,
      ),
      'trust_recovery_flows' => new ExperienceDefinition(
        id: 'trust_recovery_flows',
        category: MelExperienceContractCategory::EscalationContinuity,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        linkedWorkflowIds: ['stripe_connected'],
        continuityTriggerSignalsAll: [],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: ['vendor.guidance.needs_resume'],
        continuityPriority: 85,
        retentionTier: MelRetentionTier::Low,
        retentionImplications: 'Neutral operational guidance after trust friction — no risk scoring copy.',
        ctaSequencingNotes: 'Trust recovery defers promotional boosts.',
        accessibilityNotes: 'Explain next verified step plainly.',
        privacyBoundaries: 'Never expose trust-risk metadata publicly.',
        crossSurfaceTransitions: ['vendor_trust_recovery'],
        activationPathPrefixes: ['/vendor/trust', '/vendor/compliance'],
        requireAuthentication: TRUE,
      ),
      'dispute_refund_continuity' => new ExperienceDefinition(
        id: 'dispute_refund_continuity',
        category: MelExperienceContractCategory::EscalationContinuity,
        surfaceOwnership: [MelSurfaceId::Customer->value, MelSurfaceId::Vendor->value],
        linkedWorkflowIds: ['refund_request_started'],
        continuityTriggerSignalsAll: [],
        continuityTriggerSignalsAny: [],
        resumeGateSignalsAll: [],
        continuityPriority: 89,
        retentionTier: MelRetentionTier::None,
        retentionImplications: 'Refund/dispute UX owned by Commerce/refund modules — continuity aligns sequencing only.',
        ctaSequencingNotes: 'Single dispute/refund primary action per surface moment.',
        accessibilityNotes: 'Forms remain authoritative; banners informational only.',
        privacyBoundaries: 'Orders and disputes remain actor-permissioned.',
        crossSurfaceTransitions: ['commerce_to_support'],
        activationRoutePrefixes: ['myeventlane_refunds.'],
        activationPathPrefixes: ['/my-tickets/order'],
        requireAuthentication: TRUE,
      ),
    ];
  }

}
