<?php

declare(strict_types=1);

namespace Drupal\myeventlane_surface;

use Drupal\myeventlane_core\MelSurfaceId;
use Drupal\myeventlane_core\MelStateEvaluation;

/**
 * Single canonical catalogue of MEL intelligence orchestration contracts.
 *
 * Domain facts and workflow signals are owned elsewhere; hooks may extend
 * applicability via MelRecommendationResolver consumers and
 * hook_mel_intelligence_page_payload_alter().
 */
final class MelIntelligenceRegistry {

  /**
   * @return array<string, IntelligenceDefinition>
   */
  public function all(): array {
    return array_merge(
      $this->customerGuidance(),
      $this->vendorGuidance(),
      $this->checkoutGuidance(),
      $this->lifecycleGuidance(),
      $this->engagementGuidance(),
      $this->staffDiagnostics(),
      $this->publicDiscovery(),
    );
  }

  /**
   * @return array<string, IntelligenceDefinition>
   */
  private function customerGuidance(): array {
    $u = MelStateEvaluation::Unsatisfied;
    $s = MelStateEvaluation::Satisfied;

    return [
      'recommended_events' => new IntelligenceDefinition(
        id: 'recommended_events',
        category: MelIntelligenceContractCategory::CustomerGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Customer],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.customer'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 40,
        priorityTier: 50,
        recommendationSourceKey: 'discovery.customer_personalisation',
        ctaImplications: 'Secondary to workflow primary; never competes with checkout.',
        retentionImplications: 'Low-frequency discovery reinforcement only.',
        explainabilityNotes: 'Shown because the customer shell is active and checkout is not sensitive.',
        accessibilityNotes: 'Present as a labelled suggestion region, not an alert.',
        privacyBoundaries: 'Customer-scoped; never mixes vendor operational reasons.',
        orchestrationKind: MelEngagementOrchestrationKind::None,
      ),
      'continue_saved_event' => new IntelligenceDefinition(
        id: 'continue_saved_event',
        category: MelIntelligenceContractCategory::CustomerGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Customer],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.customer'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: TRUE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 85,
        priorityTier: 90,
        recommendationSourceKey: 'experience.resume_candidates',
        ctaImplications: 'Elevates resume/continue actions from MELExperienceSystem.',
        retentionImplications: 'Honours explicit continuation memory only.',
        explainabilityNotes: 'Shown because MELExperienceSystem reported non-empty resume candidates.',
        accessibilityNotes: 'Single primary continuation action; polite live region on change.',
        privacyBoundaries: 'Uses non-sensitive continuation keys only.',
        orchestrationKind: MelEngagementOrchestrationKind::OnboardingContinuation,
      ),
      'complete_profile_prompt' => new IntelligenceDefinition(
        id: 'complete_profile_prompt',
        category: MelIntelligenceContractCategory::CustomerGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Customer],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.customer'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: ['profile_completed' => $u],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 92,
        priorityTier: 95,
        recommendationSourceKey: 'state.profile_completed',
        ctaImplications: 'Routes to profile/settings flows governed by permissions.',
        retentionImplications: 'Defer when higher-priority checkout or support recovery is active.',
        explainabilityNotes: 'Shown because canonical profile_completed interpretation is unsatisfied.',
        accessibilityNotes: 'Adjacent to account settings patterns; not inline in checkout.',
        privacyBoundaries: 'Customer account only.',
        orchestrationKind: MelEngagementOrchestrationKind::OnboardingContinuation,
      ),
      'add_to_calendar_prompt' => new IntelligenceDefinition(
        id: 'add_to_calendar_prompt',
        category: MelIntelligenceContractCategory::CustomerGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Customer],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.customer'],
        triggerAnyOfSignals: ['route.order_detail', 'checkout.state.order_confirmed'],
        triggerBlockAnySignals: [],
        stateExpectations: ['calendar_sync_eligible' => $s],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 55,
        priorityTier: 70,
        recommendationSourceKey: 'state.calendar_sync_eligible',
        ctaImplications: 'Post-purchase calendar affordances only when eligibility is satisfied.',
        retentionImplications: 'Polite one-time style sequencing via engagement orchestrator.',
        explainabilityNotes: 'Shown after order context or confirmed checkout state plus calendar eligibility.',
        accessibilityNotes: 'Name the calendar format in link text.',
        privacyBoundaries: 'No cross-attendee data.',
        orchestrationKind: MelEngagementOrchestrationKind::CommerceContinuity,
      ),
      'revisit_recent_event' => new IntelligenceDefinition(
        id: 'revisit_recent_event',
        category: MelIntelligenceContractCategory::CustomerGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Customer],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.customer', 'customer.flags.has_orders'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 35,
        priorityTier: 45,
        recommendationSourceKey: 'workflow.customer.flags.has_orders',
        ctaImplications: 'Ticket access routes remain permission-governed.',
        retentionImplications: 'Low priority vs onboarding or support.',
        explainabilityNotes: 'Shown because the customer has prior completed orders (boolean probe only).',
        accessibilityNotes: 'Supportive tone; optional dismiss.',
        privacyBoundaries: 'No order identifiers in orchestration payload.',
        orchestrationKind: MelEngagementOrchestrationKind::ReEngagement,
      ),
      'support_followup_prompt' => new IntelligenceDefinition(
        id: 'support_followup_prompt',
        category: MelIntelligenceContractCategory::CustomerGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Customer],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.customer'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: ['support_attention' => $s],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 88,
        priorityTier: 92,
        recommendationSourceKey: 'state.support_attention',
        ctaImplications: 'Help/support entry only; messaging systems own delivery.',
        retentionImplications: 'Suppress discovery prompts when active.',
        explainabilityNotes: 'Shown because support_attention interpretation is satisfied (attention signal present, routing only).',
        accessibilityNotes: 'Clear, non-alarmist wording; visible focus target.',
        privacyBoundaries: 'No ticket contents; routing only.',
        orchestrationKind: MelEngagementOrchestrationKind::SupportRecovery,
      ),
    ];
  }

  /**
   * @return array<string, IntelligenceDefinition>
   */
  private function vendorGuidance(): array {
    $u = MelStateEvaluation::Unsatisfied;
    $s = MelStateEvaluation::Satisfied;

    return [
      'complete_vendor_setup' => new IntelligenceDefinition(
        id: 'complete_vendor_setup',
        category: MelIntelligenceContractCategory::VendorGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Vendor],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['vendor.surface.active'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [
          ['vendor_profile_completed' => $u],
          ['onboarding_complete' => $u],
        ],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 95,
        priorityTier: 100,
        recommendationSourceKey: 'onboarding.vendor_resume',
        ctaImplications: 'Aligns with MELWorkflowSystem primary onboarding CTA ordering.',
        retentionImplications: 'Highest priority until core vendor readiness satisfied.',
        explainabilityNotes: 'Shown because vendor profile or onboarding completion interpretation is unsatisfied.',
        accessibilityNotes: 'Enumerate remaining steps as text, not colour alone.',
        privacyBoundaries: 'Vendor account only.',
        orchestrationKind: MelEngagementOrchestrationKind::OnboardingContinuation,
      ),
      'connect_payouts' => new IntelligenceDefinition(
        id: 'connect_payouts',
        category: MelIntelligenceContractCategory::VendorGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Vendor],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['vendor.surface.active'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [
          ['stripe_connected' => $u],
          ['payout_ready' => $u],
        ],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 98,
        priorityTier: 100,
        recommendationSourceKey: 'state.stripe_connected_or_payout_ready',
        ctaImplications: 'Stripe/payout CTAs elevate per MELStateSystem cta_governance.',
        retentionImplications: 'Suppress boost upsell until satisfied (deterministic tier).',
        explainabilityNotes: 'Shown because Stripe connection or payout readiness interpretation is unsatisfied.',
        accessibilityNotes: 'Describe outcomes plainly; no sensitive account identifiers.',
        privacyBoundaries: 'Vendor financial readiness only.',
        orchestrationKind: MelEngagementOrchestrationKind::OnboardingContinuation,
      ),
      'publish_event_prompt' => new IntelligenceDefinition(
        id: 'publish_event_prompt',
        category: MelIntelligenceContractCategory::VendorGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Vendor],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['vendor.surface.active'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [
          'first_event_ready' => $s,
          'publishable' => $u,
        ],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 80,
        priorityTier: 85,
        recommendationSourceKey: 'state.first_event_ready_and_publishable',
        ctaImplications: 'Publish workflow primary remains authoritative.',
        retentionImplications: 'After payouts/connect, below connect_payouts tier.',
        explainabilityNotes: 'Shown because first event readiness is satisfied but publishable gate is not.',
        accessibilityNotes: 'Neutral operational tone.',
        privacyBoundaries: 'Vendor event context only.',
        orchestrationKind: MelEngagementOrchestrationKind::LifecycleFollowup,
      ),
      'boost_event_prompt' => new IntelligenceDefinition(
        id: 'boost_event_prompt',
        category: MelIntelligenceContractCategory::VendorGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Vendor],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['vendor.surface.active'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [
          'published' => $s,
          'boost_eligible' => $u,
        ],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 45,
        priorityTier: 40,
        recommendationSourceKey: 'state.published_and_boost_eligible',
        ctaImplications: 'Secondary upsell; never above payouts or moderation recovery.',
        retentionImplications: 'Low urgency sequencing.',
        explainabilityNotes: 'Shown because the event is published but boost eligibility is not satisfied.',
        accessibilityNotes: 'Avoid hype-only language.',
        privacyBoundaries: 'Vendor marketing surface only.',
        orchestrationKind: MelEngagementOrchestrationKind::None,
      ),
      'low_ticket_sales_prompt' => new IntelligenceDefinition(
        id: 'low_ticket_sales_prompt',
        category: MelIntelligenceContractCategory::VendorGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Vendor],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: [
          'vendor.surface.active',
          'vendor.guidance.low_ticket_sales_context',
        ],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: ['published' => $s],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 70,
        priorityTier: 75,
        recommendationSourceKey: 'domain.vendor.guidance.low_ticket_sales_context',
        ctaImplications: 'Commerce owning modules supply facts; intelligence sequences only.',
        retentionImplications: 'Below payouts and onboarding.',
        explainabilityNotes: 'Shown only when owning modules set vendor.guidance.low_ticket_sales_context.',
        accessibilityNotes: 'Factual tone; optional dismiss.',
        privacyBoundaries: 'Vendor-only aggregated signal; no attendee PII in orchestration.',
        orchestrationKind: MelEngagementOrchestrationKind::LifecycleFollowup,
      ),
      'attendee_engagement_prompt' => new IntelligenceDefinition(
        id: 'attendee_engagement_prompt',
        category: MelIntelligenceContractCategory::VendorGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Vendor],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: [
          'vendor.surface.active',
          'vendor.guidance.attendee_engagement_opportunity',
        ],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: ['published' => $s],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 55,
        priorityTier: 60,
        recommendationSourceKey: 'domain.vendor.guidance.attendee_engagement_opportunity',
        ctaImplications: 'Hints toward messaging/campaign systems without sending messages.',
        retentionImplications: 'Respectful density caps.',
        explainabilityNotes: 'Shown only when vendor.guidance.attendee_engagement_opportunity is provided by owning code.',
        accessibilityNotes: 'Operational, concise.',
        privacyBoundaries: 'Vendor workspace only; no cross-vendor comparisons.',
        orchestrationKind: MelEngagementOrchestrationKind::LifecycleFollowup,
      ),
      'analytics_review_prompt' => new IntelligenceDefinition(
        id: 'analytics_review_prompt',
        category: MelIntelligenceContractCategory::VendorGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Vendor],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['vendor.surface.active'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [
          'published' => $s,
          'analytics_eligible' => $s,
        ],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 38,
        priorityTier: 35,
        recommendationSourceKey: 'state.analytics_eligible',
        ctaImplications: 'Analytics frames remain permission and feature gated.',
        retentionImplications: 'Below onboarding and payouts.',
        explainabilityNotes: 'Shown because analytics eligibility and published lifecycle interpretations are satisfied.',
        accessibilityNotes: 'Offer text summaries alongside visualisations.',
        privacyBoundaries: 'Vendor analytics only.',
        orchestrationKind: MelEngagementOrchestrationKind::None,
      ),
    ];
  }

  /**
   * @return array<string, IntelligenceDefinition>
   */
  private function checkoutGuidance(): array {
    $u = MelStateEvaluation::Unsatisfied;
    $s = MelStateEvaluation::Satisfied;

    return [
      'complete_attendee_details' => new IntelligenceDefinition(
        id: 'complete_attendee_details',
        category: MelIntelligenceContractCategory::CheckoutGuidance,
        presentationLane: MelIntelligencePresentationLane::CheckoutMinimal,
        surfaceOwnership: [
          MelSurfaceId::Customer,
          MelSurfaceId::Public,
        ],
        requiresAuthentication: FALSE,
        excludeWhenCheckoutSensitive: FALSE,
        checkoutMinimalLaneOnly: TRUE,
        triggerRequireAllSignals: ['route.checkout_sensitive'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: ['attendee_complete' => $u],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 95,
        priorityTier: 95,
        recommendationSourceKey: 'state.attendee_complete',
        ctaImplications: 'Never obscures payment summary; inline field guidance only.',
        retentionImplications: 'Checkout lane max density enforced.',
        explainabilityNotes: 'Shown on checkout-sensitive routes when attendee completion interpretation is unsatisfied.',
        accessibilityNotes: 'Errors link to fields; no timer pressure.',
        privacyBoundaries: 'Checkout session only.',
        orchestrationKind: MelEngagementOrchestrationKind::CommerceContinuity,
      ),
      'retry_checkout' => new IntelligenceDefinition(
        id: 'retry_checkout',
        category: MelIntelligenceContractCategory::CheckoutGuidance,
        presentationLane: MelIntelligencePresentationLane::CheckoutMinimal,
        surfaceOwnership: [
          MelSurfaceId::Customer,
          MelSurfaceId::Public,
        ],
        requiresAuthentication: FALSE,
        excludeWhenCheckoutSensitive: FALSE,
        checkoutMinimalLaneOnly: TRUE,
        triggerRequireAllSignals: [
          'route.checkout_sensitive',
          'route.commerce_checkout',
          'checkout.state.recoverable_failure',
        ],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 97,
        priorityTier: 98,
        recommendationSourceKey: 'domain.checkout.state.recoverable_failure',
        ctaImplications: 'Commerce retry flows own behaviour; this is copy/sequencing only.',
        retentionImplications: 'Single prominent recovery hint.',
        explainabilityNotes: 'Shown when checkout.state.recoverable_failure is set by Commerce integration (deterministic).',
        accessibilityNotes: 'Clear retry target; no deceptive urgency.',
        privacyBoundaries: 'No cross-account error sharing.',
        orchestrationKind: MelEngagementOrchestrationKind::CommerceContinuity,
      ),
      'add_wallet_prompt' => new IntelligenceDefinition(
        id: 'add_wallet_prompt',
        category: MelIntelligenceContractCategory::CheckoutGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Customer],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.customer', 'route.order_detail'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: ['order_confirmed' => $s],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 50,
        priorityTier: 65,
        recommendationSourceKey: 'route.order_detail_and_order_confirmed',
        ctaImplications: 'Wallet/add-to-device links are optional secondary actions.',
        retentionImplications: 'Post-purchase only.',
        explainabilityNotes: 'Shown on order detail route with satisfied order_confirmed interpretation.',
        accessibilityNotes: 'Describe wallet provider in visible text.',
        privacyBoundaries: 'Customer order surface only.',
        orchestrationKind: MelEngagementOrchestrationKind::CommerceContinuity,
      ),
      'share_event_prompt' => new IntelligenceDefinition(
        id: 'share_event_prompt',
        category: MelIntelligenceContractCategory::CheckoutGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Customer],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.customer'],
        triggerAnyOfSignals: ['route.order_detail', 'route.rsvp_thankyou'],
        triggerBlockAnySignals: [],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 42,
        priorityTier: 55,
        recommendationSourceKey: 'route.post_purchase_thankyou_or_order_detail',
        ctaImplications: 'Share actions are secondary to tickets/receipt.',
        retentionImplications: 'Low pressure.',
        explainabilityNotes: 'Shown on post-purchase confirmation contexts (route signals).',
        accessibilityNotes: 'Social share controls labelled plainly.',
        privacyBoundaries: 'No unintended public visibility of private events.',
        orchestrationKind: MelEngagementOrchestrationKind::CommerceContinuity,
      ),
      'order_followup_prompt' => new IntelligenceDefinition(
        id: 'order_followup_prompt',
        category: MelIntelligenceContractCategory::CheckoutGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Customer],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.customer', 'route.order_detail'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 48,
        priorityTier: 60,
        recommendationSourceKey: 'route.order_detail',
        ctaImplications: 'Support and ticket access follow Commerce permissions.',
        retentionImplications: 'Polite follow-up tone.',
        explainabilityNotes: 'Shown on canonical order detail route in customer shell.',
        accessibilityNotes: 'Group next steps in one landmark.',
        privacyBoundaries: 'Customer order scope only.',
        orchestrationKind: MelEngagementOrchestrationKind::CommerceContinuity,
      ),
    ];
  }

  /**
   * @return array<string, IntelligenceDefinition>
   */
  private function lifecycleGuidance(): array {
    $u = MelStateEvaluation::Unsatisfied;
    $s = MelStateEvaluation::Satisfied;

    return [
      'draft_completion_prompt' => new IntelligenceDefinition(
        id: 'draft_completion_prompt',
        category: MelIntelligenceContractCategory::LifecycleGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Vendor],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['vendor.surface.active'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [
          ['draft' => $s],
          ['incomplete' => $s],
        ],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 78,
        priorityTier: 80,
        recommendationSourceKey: 'state.draft_or_incomplete',
        ctaImplications: 'Studio entry CTAs follow existing workflow routing.',
        retentionImplications: 'Above boost upsell.',
        explainabilityNotes: 'Shown when draft or incomplete lifecycle interpretation is satisfied (operational cue).',
        accessibilityNotes: 'Neutral “draft” wording.',
        privacyBoundaries: 'Vendor/staff contexts only.',
        orchestrationKind: MelEngagementOrchestrationKind::LifecycleFollowup,
      ),
      'sold_out_momentum_prompt' => new IntelligenceDefinition(
        id: 'sold_out_momentum_prompt',
        category: MelIntelligenceContractCategory::LifecycleGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Vendor],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['vendor.surface.active'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: ['sold_out' => $s],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 60,
        priorityTier: 62,
        recommendationSourceKey: 'state.sold_out',
        ctaImplications: 'Operational next steps (waitlist, future dates) — product routes own links.',
        retentionImplications: 'Non-urgent.',
        explainabilityNotes: 'Shown because sold_out lifecycle interpretation is satisfied.',
        accessibilityNotes: 'Avoid false scarcity timers.',
        privacyBoundaries: 'Vendor event context.',
        orchestrationKind: MelEngagementOrchestrationKind::LifecycleFollowup,
      ),
      'cancelled_event_followup' => new IntelligenceDefinition(
        id: 'cancelled_event_followup',
        category: MelIntelligenceContractCategory::LifecycleGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Vendor],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['vendor.surface.active'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: ['cancelled' => $s],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 82,
        priorityTier: 85,
        recommendationSourceKey: 'state.cancelled',
        ctaImplications: 'Refund/help flows remain Commerce-governed.',
        retentionImplications: 'Supportive sequencing.',
        explainabilityNotes: 'Shown because cancelled lifecycle interpretation is satisfied.',
        accessibilityNotes: 'Clear, respectful copy.',
        privacyBoundaries: 'Vendor operational only.',
        orchestrationKind: MelEngagementOrchestrationKind::LifecycleFollowup,
      ),
      'moderation_recovery_prompt' => new IntelligenceDefinition(
        id: 'moderation_recovery_prompt',
        category: MelIntelligenceContractCategory::LifecycleGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Vendor],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['vendor.surface.active'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: ['moderation_hold' => $s],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 99,
        priorityTier: 100,
        recommendationSourceKey: 'state.moderation_hold',
        ctaImplications: 'Defer competing CTAs per MELStateSystem during holds.',
        retentionImplications: 'Suppress engagement nudges.',
        explainabilityNotes: 'Shown because moderation_hold interpretation is satisfied on vendor shell (actionable but vague).',
        accessibilityNotes: 'No internal moderator details.',
        privacyBoundaries: 'No moderation internals; vendor-safe wording only.',
        orchestrationKind: MelEngagementOrchestrationKind::SupportRecovery,
      ),
    ];
  }

  /**
   * @return array<string, IntelligenceDefinition>
   */
  private function engagementGuidance(): array {
    return [
      're_engagement_prompt' => new IntelligenceDefinition(
        id: 're_engagement_prompt',
        category: MelIntelligenceContractCategory::EngagementGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Customer],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.customer'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: 'low',
        priorityWeight: 50,
        priorityTier: 58,
        recommendationSourceKey: 'experience.retention_tier',
        ctaImplications: 'Single soft return CTA.',
        retentionImplications: 'Gated by MELExperienceSystem retention tier.',
        explainabilityNotes: 'Shown when experience retention tier is at least low.',
        accessibilityNotes: 'Polite live region; dismissible.',
        privacyBoundaries: 'Customer account only.',
        orchestrationKind: MelEngagementOrchestrationKind::ReEngagement,
      ),
      'incomplete_onboarding_prompt' => new IntelligenceDefinition(
        id: 'incomplete_onboarding_prompt',
        category: MelIntelligenceContractCategory::EngagementGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Vendor],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['vendor.surface.active', 'vendor.guidance.needs_resume'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 90,
        priorityTier: 92,
        recommendationSourceKey: 'workflow.vendor.guidance.needs_resume',
        ctaImplications: 'Resume onboarding aligns with MELWorkflowSystem.',
        retentionImplications: 'Coordinate with complete_vendor_setup (orchestrator density).',
        explainabilityNotes: 'Shown because vendor.guidance.needs_resume workflow signal is present.',
        accessibilityNotes: 'One primary resume action.',
        privacyBoundaries: 'Vendor account only.',
        orchestrationKind: MelEngagementOrchestrationKind::OnboardingContinuation,
      ),
      'incomplete_customer_onboarding_prompt' => new IntelligenceDefinition(
        id: 'incomplete_customer_onboarding_prompt',
        category: MelIntelligenceContractCategory::EngagementGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Customer],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.customer', 'customer.guidance.needs_resume'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 88,
        priorityTier: 90,
        recommendationSourceKey: 'workflow.customer.guidance.needs_resume',
        ctaImplications: 'Resume customer onboarding aligns with MELWorkflowSystem; does not replace onboarding routes.',
        retentionImplications: 'Deduped with other onboarding continuation rows by engagement orchestrator.',
        explainabilityNotes: 'Shown when a customer-track onboarding row exists and is not completed (read-only probe).',
        accessibilityNotes: 'One primary resume action; supportive tone.',
        privacyBoundaries: 'Customer account only; no vendor data.',
        orchestrationKind: MelEngagementOrchestrationKind::OnboardingContinuation,
      ),
      'return_to_platform_prompt' => new IntelligenceDefinition(
        id: 'return_to_platform_prompt',
        category: MelIntelligenceContractCategory::EngagementGuidance,
        presentationLane: MelIntelligencePresentationLane::Guidance,
        surfaceOwnership: [MelSurfaceId::Customer],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: TRUE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.customer'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: 'medium',
        priorityWeight: 52,
        priorityTier: 60,
        recommendationSourceKey: 'experience.retention_tier',
        ctaImplications: 'Gentle dashboard nudge.',
        retentionImplications: 'Medium tier only (respectful frequency).',
        explainabilityNotes: 'Shown when experience retention tier is medium.',
        accessibilityNotes: 'Avoid manipulative urgency.',
        privacyBoundaries: 'Customer account only.',
        orchestrationKind: MelEngagementOrchestrationKind::ReEngagement,
      ),
      'trust_building_prompt' => new IntelligenceDefinition(
        id: 'trust_building_prompt',
        category: MelIntelligenceContractCategory::EngagementGuidance,
        presentationLane: MelIntelligencePresentationLane::PublicDiscovery,
        surfaceOwnership: [MelSurfaceId::Public],
        requiresAuthentication: FALSE,
        excludeWhenCheckoutSensitive: FALSE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.public'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: ['route.checkout_sensitive'],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 20,
        priorityTier: 25,
        recommendationSourceKey: 'surface.public_trust_copy',
        ctaImplications: 'Non-invasive trust panels only.',
        retentionImplications: 'Very low density on public shell.',
        explainabilityNotes: 'Shown on public surface outside checkout-sensitive paths.',
        accessibilityNotes: 'Static informational tone.',
        privacyBoundaries: 'No personalised claims without authentication.',
        orchestrationKind: MelEngagementOrchestrationKind::None,
      ),
    ];
  }

  /**
   * @return array<string, IntelligenceDefinition>
   */
  private function staffDiagnostics(): array {
    $s = MelStateEvaluation::Satisfied;

    return [
      'staff_trust_escalation_diagnostic' => new IntelligenceDefinition(
        id: 'staff_trust_escalation_diagnostic',
        category: MelIntelligenceContractCategory::StaffDiagnostic,
        presentationLane: MelIntelligencePresentationLane::StaffDiagnostic,
        surfaceOwnership: [MelSurfaceId::Staff],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: FALSE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.staff'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: ['escalation_review' => $s],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 100,
        priorityTier: 100,
        recommendationSourceKey: 'state.escalation_review',
        ctaImplications: 'Staff queues and tools own navigation.',
        retentionImplications: 'Diagnostics only.',
        explainabilityNotes: 'Staff-only diagnostic when escalation_review interpretation is satisfied.',
        accessibilityNotes: 'Landmark diagnostic region; separate from public marketing.',
        privacyBoundaries: 'Staff role boundaries enforced server-side; no customer-facing leakage.',
        orchestrationKind: MelEngagementOrchestrationKind::SupportRecovery,
      ),
      'staff_moderation_hold_diagnostic' => new IntelligenceDefinition(
        id: 'staff_moderation_hold_diagnostic',
        category: MelIntelligenceContractCategory::StaffDiagnostic,
        presentationLane: MelIntelligencePresentationLane::StaffDiagnostic,
        surfaceOwnership: [MelSurfaceId::Staff],
        requiresAuthentication: TRUE,
        excludeWhenCheckoutSensitive: FALSE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.staff'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: [],
        stateExpectations: ['moderation_hold' => $s],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 99,
        priorityTier: 100,
        recommendationSourceKey: 'state.moderation_hold',
        ctaImplications: 'Moderation tools own actions.',
        retentionImplications: 'Diagnostics only.',
        explainabilityNotes: 'Staff-only diagnostic when moderation_hold interpretation is satisfied.',
        accessibilityNotes: 'Operational phrasing appropriate to staff shells.',
        privacyBoundaries: 'Do not surface internals to vendors or customers via this payload.',
        orchestrationKind: MelEngagementOrchestrationKind::SupportRecovery,
      ),
    ];
  }

  /**
   * @return array<string, IntelligenceDefinition>
   */
  private function publicDiscovery(): array {
    return [
      'public_discovery_events_hint' => new IntelligenceDefinition(
        id: 'public_discovery_events_hint',
        category: MelIntelligenceContractCategory::EngagementGuidance,
        presentationLane: MelIntelligencePresentationLane::PublicDiscovery,
        surfaceOwnership: [MelSurfaceId::Public],
        requiresAuthentication: FALSE,
        excludeWhenCheckoutSensitive: FALSE,
        checkoutMinimalLaneOnly: FALSE,
        triggerRequireAllSignals: ['surface.public'],
        triggerAnyOfSignals: [],
        triggerBlockAnySignals: ['route.checkout_sensitive', 'route.auth_login'],
        stateExpectations: [],
        stateExpectationAlternativeGroups: [],
        requiresNonEmptyResume: FALSE,
        requiresRetentionTierMin: NULL,
        priorityWeight: 25,
        priorityTier: 30,
        recommendationSourceKey: 'discovery.public_listings',
        ctaImplications: 'Discovery CTAs follow existing routes.',
        retentionImplications: 'Non-invasive; capped density.',
        explainabilityNotes: 'Shown on public marketing/discovery contexts excluding checkout and login.',
        accessibilityNotes: 'Optional panel; not an alert.',
        privacyBoundaries: 'Anonymous-safe; no account inference.',
        orchestrationKind: MelEngagementOrchestrationKind::None,
      ),
    ];
  }

}
