<?php

declare(strict_types=1);

namespace Drupal\myeventlane_surface;

use Drupal\myeventlane_core\MelSurfaceId;

/**
 * Single canonical catalogue of MEL state interpretation contracts.
 */
final class MelStateRegistry {

  /**
   * @return array<string, \Drupal\myeventlane_surface\StateDefinition>
   */
  public function all(): array {
    return [
      // --- Account readiness: customer ---------------------------------------
      'account_created' => new StateDefinition(
        id: 'account_created',
        category: MelStateContractCategory::AccountReadinessCustomer,
        surfaceOwnership: [MelSurfaceId::Customer->value],
        sourceSystems: ['drupal_user'],
        interpretationRuleSummary: 'Satisfied when the shopper shell is active and the account is authenticated; extend via mel_state_domain_facts.',
        requiredPositiveSignals: ['surface.customer'],
        blockingSignals: [],
        severity: MelStateSeverity::Low,
        uxImplications: 'Customer shell tone stays reassuring; avoid operational jargon.',
        ctaImplications: 'Default CTAs follow MELWorkflowSystem; no extra gates here.',
        accessibilityNotes: 'Treat account milestones as status semantics, not alerts.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'profile_completed' => new StateDefinition(
        id: 'profile_completed',
        category: MelStateContractCategory::AccountReadinessCustomer,
        surfaceOwnership: [MelSurfaceId::Customer->value],
        sourceSystems: ['drupal_profile', 'workflow_signals'],
        interpretationRuleSummary: 'Maps to workflow signal customer.profile.complete.',
        requiredPositiveSignals: ['customer.profile.complete'],
        blockingSignals: [],
        severity: MelStateSeverity::Medium,
        uxImplications: 'Incomplete profile messaging stays adjacent to form validation, not a duplicate gate.',
        ctaImplications: 'Profile completion prompts defer to workflow primary CTA ordering.',
        accessibilityNotes: 'Keep profile status in labelled regions; don’t rely on colour alone.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'first_booking_completed' => new StateDefinition(
        id: 'first_booking_completed',
        category: MelStateContractCategory::AccountReadinessCustomer,
        surfaceOwnership: [MelSurfaceId::Customer->value],
        sourceSystems: ['commerce_order', 'onboarding'],
        interpretationRuleSummary: 'Maps to customer.flags.has_orders from onboarding probe.',
        requiredPositiveSignals: ['customer.flags.has_orders'],
        blockingSignals: [],
        severity: MelStateSeverity::Medium,
        uxImplications: 'Celebrates first purchase without exposing order internals.',
        ctaImplications: 'Ticket access CTAs follow Commerce permissions plus workflow hints.',
        accessibilityNotes: 'Order milestones use polite live regions on confirmation pages only.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'notification_preferences_complete' => new StateDefinition(
        id: 'notification_preferences_complete',
        category: MelStateContractCategory::AccountReadinessCustomer,
        surfaceOwnership: [MelSurfaceId::Customer->value],
        sourceSystems: ['drupal_profile'],
        interpretationRuleSummary: 'Requires domain fact customer.readiness.notifications_complete from owning modules.',
        requiredPositiveSignals: ['customer.readiness.notifications_complete'],
        blockingSignals: [],
        severity: MelStateSeverity::Low,
        uxImplications: 'Prompt in settings context only; never inline checkout.',
        ctaImplications: 'Secondary to ticketing CTAs.',
        accessibilityNotes: 'Describe channels plainly; pair icons with text.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),

      // --- Account readiness: vendor -----------------------------------------
      'vendor_profile_completed' => new StateDefinition(
        id: 'vendor_profile_completed',
        category: MelStateContractCategory::AccountReadinessVendor,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        sourceSystems: ['onboarding', 'drupal_profile'],
        interpretationRuleSummary: 'Proxy satisfied when vendor organisation exists (vendor.flags.has_vendor); refine with mel_state_domain_facts.',
        requiredPositiveSignals: ['vendor.flags.has_vendor'],
        blockingSignals: [],
        severity: MelStateSeverity::High,
        uxImplications: 'Operational copy; link to onboarding resume when unsatisfied.',
        ctaImplications: 'Profile/setup CTAs elevate until satisfied.',
        accessibilityNotes: 'Landmarks for setup panels; maintain focus order.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'stripe_connected' => new StateDefinition(
        id: 'stripe_connected',
        category: MelStateContractCategory::AccountReadinessVendor,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        sourceSystems: ['stripe_connect', 'onboarding'],
        interpretationRuleSummary: 'Maps to vendor.flags.stripe_connected onboarding flag.',
        requiredPositiveSignals: ['vendor.flags.stripe_connected'],
        blockingSignals: [],
        severity: MelStateSeverity::Critical,
        uxImplications: 'Charge readiness messaging stays factual; never imply access bypass.',
        ctaImplications: 'Stripe connection CTA elevates until satisfied when onboarding active.',
        accessibilityNotes: 'Describe outcomes (payouts/charges) clearly; no sensitive account IDs in labels.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'payout_ready' => new StateDefinition(
        id: 'payout_ready',
        category: MelStateContractCategory::AccountReadinessVendor,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        sourceSystems: ['stripe_connect'],
        interpretationRuleSummary: 'Requires domain fact vendor.readiness.payout_ready set by Stripe/Commerce owning code.',
        requiredPositiveSignals: ['vendor.readiness.payout_ready'],
        blockingSignals: [],
        severity: MelStateSeverity::High,
        uxImplications: 'Differentiate connection vs payout capability.',
        ctaImplications: 'Dashboard transfers/payout CTAs follow this interpretation.',
        accessibilityNotes: 'Avoid alarmist language; provide next step links.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'onboarding_complete' => new StateDefinition(
        id: 'onboarding_complete',
        category: MelStateContractCategory::AccountReadinessVendor,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        sourceSystems: ['onboarding'],
        interpretationRuleSummary: 'Maps to vendor.onboarding.completed.',
        requiredPositiveSignals: ['vendor.onboarding.completed'],
        blockingSignals: [],
        severity: MelStateSeverity::Medium,
        uxImplications: 'Completion reduces guided prompts; operational surfaces remain dense.',
        ctaImplications: 'Suppress redundant onboarding CTAs when satisfied.',
        accessibilityNotes: 'Announce completion once; avoid duplicate success regions.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'first_event_ready' => new StateDefinition(
        id: 'first_event_ready',
        category: MelStateContractCategory::AccountReadinessVendor,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        sourceSystems: ['onboarding', 'drupal_node'],
        interpretationRuleSummary: 'Requires events and ticket configuration flags from onboarding signals.',
        requiredPositiveSignals: ['vendor.flags.has_events', 'vendor.flags.has_tickets'],
        blockingSignals: [],
        severity: MelStateSeverity::High,
        uxImplications: 'Signals readiness for paid operations; does not replace publish gates.',
        ctaImplications: 'Ticket sales CTAs align with this plus commerce safety.',
        accessibilityNotes: 'Checklists should enumerate remaining steps accessibly.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),

      // --- Event lifecycle ---------------------------------------------------
      'draft' => new StateDefinition(
        id: 'draft',
        category: MelStateContractCategory::EventLifecycle,
        surfaceOwnership: [],
        sourceSystems: ['drupal_node', 'workflow_signals'],
        interpretationRuleSummary: 'Domain fact event.lifecycle.draft set by event-owning code.',
        requiredPositiveSignals: ['event.lifecycle.draft'],
        blockingSignals: [],
        severity: MelStateSeverity::Low,
        uxImplications: 'Vendor/staff diagnostic; public surfaces ignore unless explicitly safe.',
        ctaImplications: 'Publish CTAs remain suppressed except via publishable interpretation.',
        accessibilityNotes: 'Use neutral “draft” terminology on vendor/staff only.',
        requiresAuthentication: FALSE,
        publicSafe: FALSE,
      ),
      'incomplete' => new StateDefinition(
        id: 'incomplete',
        category: MelStateContractCategory::EventLifecycle,
        surfaceOwnership: [],
        sourceSystems: ['drupal_node', 'event_studio'],
        interpretationRuleSummary: 'Domain fact event.lifecycle.incomplete.',
        requiredPositiveSignals: ['event.lifecycle.incomplete'],
        blockingSignals: [],
        severity: MelStateSeverity::Medium,
        uxImplications: 'Highlights missingSteps-style UX without duplicating validation lists.',
        ctaImplications: 'Completion CTAs route to Event Studio entry points.',
        accessibilityNotes: 'Summaries precede detailed lists for screen readers.',
        requiresAuthentication: FALSE,
        publicSafe: FALSE,
      ),
      'publishable' => new StateDefinition(
        id: 'publishable',
        category: MelStateContractCategory::EventLifecycle,
        surfaceOwnership: [],
        sourceSystems: ['drupal_node', 'moderation', 'commerce_product'],
        interpretationRuleSummary: 'Fact event.lifecycle.publishable; blocked when hold/cancelled/archived.',
        requiredPositiveSignals: ['event.lifecycle.publishable'],
        blockingSignals: [
          'event.lifecycle.moderation_hold',
          'event.lifecycle.cancelled',
          'event.lifecycle.archived',
        ],
        severity: MelStateSeverity::High,
        uxImplications: 'Enables publish CTA interpretation only; access still enforced server-side.',
        ctaImplications: 'Publish CTA allowed only when Satisfied and routes permit.',
        accessibilityNotes: 'Pair warnings if unsatisfied; never colour-only.',
        requiresAuthentication: FALSE,
        publicSafe: FALSE,
      ),
      'published' => new StateDefinition(
        id: 'published',
        category: MelStateContractCategory::EventLifecycle,
        surfaceOwnership: [],
        sourceSystems: ['drupal_node'],
        interpretationRuleSummary: 'Domain fact event.lifecycle.published.',
        requiredPositiveSignals: ['event.lifecycle.published'],
        blockingSignals: [],
        severity: MelStateSeverity::Info,
        uxImplications: 'Lifecycle chips for dashboards and public listings.',
        ctaImplications: 'Boost/eligibility CTAs may unlock downstream.',
        accessibilityNotes: 'Chip text includes full status words.',
        requiresAuthentication: FALSE,
        publicSafe: TRUE,
      ),
      'boosted' => new StateDefinition(
        id: 'boosted',
        category: MelStateContractCategory::EventLifecycle,
        surfaceOwnership: [],
        sourceSystems: ['boost', 'drupal_node'],
        interpretationRuleSummary: 'Domain fact event.lifecycle.boosted.',
        requiredPositiveSignals: ['event.lifecycle.boosted'],
        blockingSignals: [],
        severity: MelStateSeverity::Low,
        uxImplications: 'Marketing accent without obscuring operational status.',
        ctaImplications: 'Boost management CTAs follow feature eligibility.',
        accessibilityNotes: 'Avoid flashing indicators; respect reduced motion.',
        requiresAuthentication: FALSE,
        publicSafe: TRUE,
      ),
      'sold_out' => new StateDefinition(
        id: 'sold_out',
        category: MelStateContractCategory::EventLifecycle,
        surfaceOwnership: [],
        sourceSystems: ['commerce_inventory', 'drupal_node'],
        interpretationRuleSummary: 'Domain fact event.lifecycle.sold_out.',
        requiredPositiveSignals: ['event.lifecycle.sold_out'],
        blockingSignals: [],
        severity: MelStateSeverity::Medium,
        uxImplications: 'Replace purchase CTAs with waitlist/support messaging per product.',
        ctaImplications: 'Purchase CTAs interpreted as hidden/disabled.',
        accessibilityNotes: 'Announce availability changes politely.',
        requiresAuthentication: FALSE,
        publicSafe: TRUE,
      ),
      'cancelled' => new StateDefinition(
        id: 'cancelled',
        category: MelStateContractCategory::EventLifecycle,
        surfaceOwnership: [],
        sourceSystems: ['drupal_node'],
        interpretationRuleSummary: 'Domain fact event.lifecycle.cancelled.',
        requiredPositiveSignals: ['event.lifecycle.cancelled'],
        blockingSignals: [],
        severity: MelStateSeverity::High,
        uxImplications: 'Suppress purchase/boost CTAs; show support paths.',
        ctaImplications: 'Refund/help CTAs follow Commerce permissions.',
        accessibilityNotes: 'Use assertive messaging only for blocking errors, otherwise status role.',
        requiresAuthentication: FALSE,
        publicSafe: TRUE,
      ),
      'archived' => new StateDefinition(
        id: 'archived',
        category: MelStateContractCategory::EventLifecycle,
        surfaceOwnership: [],
        sourceSystems: ['drupal_node'],
        interpretationRuleSummary: 'Domain fact event.lifecycle.archived.',
        requiredPositiveSignals: ['event.lifecycle.archived'],
        blockingSignals: [],
        severity: MelStateSeverity::Medium,
        uxImplications: 'Read-only presentation; no operational CTAs.',
        ctaImplications: 'Hide publish/sales/boost CTAs.',
        accessibilityNotes: 'Label archived clearly on vendor/staff surfaces.',
        requiresAuthentication: FALSE,
        publicSafe: FALSE,
      ),
      'moderation_hold' => new StateDefinition(
        id: 'moderation_hold',
        category: MelStateContractCategory::EventLifecycle,
        surfaceOwnership: [],
        sourceSystems: ['moderation'],
        interpretationRuleSummary: 'Domain fact event.lifecycle.moderation_hold; never expose internals publicly.',
        requiredPositiveSignals: ['event.lifecycle.moderation_hold'],
        blockingSignals: [],
        severity: MelStateSeverity::Critical,
        uxImplications: 'Staff: diagnostic. Vendor: actionable but vague. Public: hide details.',
        ctaImplications: 'Defer workflow primary CTA on sensitive routes when hold active.',
        accessibilityNotes: 'Staff-only escalation wording; public-safe copy elsewhere.',
        requiresAuthentication: FALSE,
        publicSafe: FALSE,
      ),

      // --- Checkout (interpretation only) -----------------------------------
      'cart_ready' => new StateDefinition(
        id: 'cart_ready',
        category: MelStateContractCategory::Checkout,
        surfaceOwnership: [
          MelSurfaceId::Public->value,
          MelSurfaceId::Customer->value,
        ],
        sourceSystems: ['commerce_cart'],
        interpretationRuleSummary: 'Fact checkout.state.cart_ready from checkout-owning modules.',
        requiredPositiveSignals: ['checkout.state.cart_ready'],
        blockingSignals: [],
        severity: MelStateSeverity::Low,
        uxImplications: 'Checkout-friendly tone; minimal chrome.',
        ctaImplications: 'Proceed-to-checkout CTAs align with cart readiness.',
        accessibilityNotes: 'Cart updates should not steal focus.',
        requiresAuthentication: FALSE,
        publicSafe: FALSE,
      ),
      'attendee_complete' => new StateDefinition(
        id: 'attendee_complete',
        category: MelStateContractCategory::Checkout,
        surfaceOwnership: [
          MelSurfaceId::Public->value,
          MelSurfaceId::Customer->value,
        ],
        sourceSystems: ['commerce_checkout'],
        interpretationRuleSummary: 'Fact checkout.state.attendee_complete.',
        requiredPositiveSignals: ['checkout.state.attendee_complete'],
        blockingSignals: [],
        severity: MelStateSeverity::Medium,
        uxImplications: 'Surface readiness only; validation remains with Commerce panes.',
        ctaImplications: 'Payment step CTAs gated behind completeness.',
        accessibilityNotes: 'Errors remain field-attached; this layer never replaces them.',
        requiresAuthentication: FALSE,
        publicSafe: FALSE,
      ),
      'payment_processing' => new StateDefinition(
        id: 'payment_processing',
        category: MelStateContractCategory::Checkout,
        surfaceOwnership: [
          MelSurfaceId::Public->value,
          MelSurfaceId::Customer->value,
        ],
        sourceSystems: ['commerce_payment'],
        interpretationRuleSummary: 'Fact checkout.state.payment_processing.',
        requiredPositiveSignals: ['checkout.state.payment_processing'],
        blockingSignals: [],
        severity: MelStateSeverity::High,
        uxImplications: 'Show processing state; avoid competing CTAs.',
        ctaImplications: 'Defer workflow primary CTA while processing.',
        accessibilityNotes: 'Loading semantics with polite aria-live.',
        requiresAuthentication: FALSE,
        publicSafe: FALSE,
      ),
      'payment_complete' => new StateDefinition(
        id: 'payment_complete',
        category: MelStateContractCategory::Checkout,
        surfaceOwnership: [
          MelSurfaceId::Public->value,
          MelSurfaceId::Customer->value,
        ],
        sourceSystems: ['commerce_payment'],
        interpretationRuleSummary: 'Fact checkout.state.payment_complete.',
        requiredPositiveSignals: ['checkout.state.payment_complete'],
        blockingSignals: [],
        severity: MelStateSeverity::Info,
        uxImplications: 'Short-lived success before redirect.',
        ctaImplications: 'Transition to order confirmation interpretation.',
        accessibilityNotes: 'Announce success once.',
        requiresAuthentication: FALSE,
        publicSafe: FALSE,
      ),
      'order_confirmed' => new StateDefinition(
        id: 'order_confirmed',
        category: MelStateContractCategory::Checkout,
        surfaceOwnership: [MelSurfaceId::Customer->value],
        sourceSystems: ['commerce_order'],
        interpretationRuleSummary: 'Uses route.order_detail signal or checkout.state.order_confirmed fact.',
        requiredPositiveSignals: ['checkout.state.order_confirmed'],
        blockingSignals: [],
        severity: MelStateSeverity::Info,
        uxImplications: 'Confirmation tone; ticket access emphasis.',
        ctaImplications: 'Calendar/download CTAs follow workflow ordering.',
        accessibilityNotes: 'Summaries must not leak other customers’ data.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'refund_pending' => new StateDefinition(
        id: 'refund_pending',
        category: MelStateContractCategory::Checkout,
        surfaceOwnership: [MelSurfaceId::Customer->value, MelSurfaceId::Vendor->value],
        sourceSystems: ['commerce_order'],
        interpretationRuleSummary: 'Fact checkout.state.refund_pending; never expose processor internals.',
        requiredPositiveSignals: ['checkout.state.refund_pending'],
        blockingSignals: [],
        severity: MelStateSeverity::Medium,
        uxImplications: 'Neutral operational status for entitled roles only.',
        ctaImplications: 'Support/refund CTAs per permissions.',
        accessibilityNotes: 'Avoid sharing amounts PII in live regions.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'refunded' => new StateDefinition(
        id: 'refunded',
        category: MelStateContractCategory::Checkout,
        surfaceOwnership: [MelSurfaceId::Customer->value, MelSurfaceId::Vendor->value],
        sourceSystems: ['commerce_order'],
        interpretationRuleSummary: 'Fact checkout.state.refunded.',
        requiredPositiveSignals: ['checkout.state.refunded'],
        blockingSignals: [],
        severity: MelStateSeverity::Info,
        uxImplications: 'Closure messaging; ticket invalidation copy per product.',
        ctaImplications: 'Hide payment capture CTAs.',
        accessibilityNotes: 'Plain language status.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),

      // --- Trust -------------------------------------------------------------
      'verified_vendor' => new StateDefinition(
        id: 'verified_vendor',
        category: MelStateContractCategory::Trust,
        surfaceOwnership: [],
        sourceSystems: ['moderation', 'stripe_connect'],
        interpretationRuleSummary: 'Fact trust.verified_vendor; safe public indicator only when modules mark public-safe.',
        requiredPositiveSignals: ['trust.verified_vendor'],
        blockingSignals: [],
        severity: MelStateSeverity::Low,
        uxImplications: 'Public listings may show badge; no backstage detail.',
        ctaImplications: 'None directly; reinforces browse confidence.',
        accessibilityNotes: 'Badge text includes “verified organiser” wording.',
        requiresAuthentication: FALSE,
        publicSafe: TRUE,
      ),
      'payout_verified' => new StateDefinition(
        id: 'payout_verified',
        category: MelStateContractCategory::Trust,
        surfaceOwnership: [MelSurfaceId::Vendor->value, MelSurfaceId::Staff->value],
        sourceSystems: ['stripe_connect'],
        interpretationRuleSummary: 'Fact trust.payout_verified; not for public.',
        requiredPositiveSignals: ['trust.payout_verified'],
        blockingSignals: [],
        severity: MelStateSeverity::Medium,
        uxImplications: 'Vendor/staff operational confidence.',
        ctaImplications: 'Supports transfers dashboards.',
        accessibilityNotes: 'Avoid sharing bank metadata.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'moderation_safe' => new StateDefinition(
        id: 'moderation_safe',
        category: MelStateContractCategory::Trust,
        surfaceOwnership: [MelSurfaceId::Staff->value, MelSurfaceId::Vendor->value],
        sourceSystems: ['moderation'],
        interpretationRuleSummary: 'Fact trust.moderation_safe; coarse-grained only.',
        requiredPositiveSignals: ['trust.moderation_safe'],
        blockingSignals: [],
        severity: MelStateSeverity::Low,
        uxImplications: 'Positive trust chip without investigation detail.',
        ctaImplications: 'Does not unlock publish alone.',
        accessibilityNotes: 'Staff diagnostic tone permitted.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'flagged' => new StateDefinition(
        id: 'flagged',
        category: MelStateContractCategory::Trust,
        surfaceOwnership: [MelSurfaceId::Staff->value, MelSurfaceId::Vendor->value],
        sourceSystems: ['moderation'],
        interpretationRuleSummary: 'Fact trust.flagged; never exposed on Public customer surfaces.',
        requiredPositiveSignals: ['trust.flagged'],
        blockingSignals: [],
        severity: MelStateSeverity::High,
        uxImplications: 'Vendor-facing vague warning; staff sees tooling elsewhere.',
        ctaImplications: 'Escalate to resolution workflows; does not replace moderation queues.',
        accessibilityNotes: 'Use alert role only when action required.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'escalation_review' => new StateDefinition(
        id: 'escalation_review',
        category: MelStateContractCategory::Trust,
        surfaceOwnership: [MelSurfaceId::Staff->value, MelSurfaceId::Vendor->value],
        sourceSystems: ['support', 'moderation'],
        interpretationRuleSummary: 'Fact trust.escalation_review or support.flags.escalation workflow signal.',
        requiredPositiveSignals: ['trust.escalation_review'],
        blockingSignals: [],
        severity: MelStateSeverity::Critical,
        uxImplications: 'Staff diagnostic; vendor sees limited messaging.',
        ctaImplications: 'Workflow primary may emphasise escalation handling.',
        accessibilityNotes: 'Differentiate assertive vs polite delivery by severity.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'support_attention' => new StateDefinition(
        id: 'support_attention',
        category: MelStateContractCategory::Trust,
        surfaceOwnership: [
          MelSurfaceId::Customer->value,
          MelSurfaceId::Vendor->value,
          MelSurfaceId::Staff->value,
        ],
        sourceSystems: ['support'],
        interpretationRuleSummary: 'Fact trust.support_attention for open cases.',
        requiredPositiveSignals: ['trust.support_attention'],
        blockingSignals: [],
        severity: MelStateSeverity::Medium,
        uxImplications: 'Encourage contact/help without exposing case internals.',
        ctaImplications: 'Help CTAs elevate moderately.',
        accessibilityNotes: 'Summaries are user-specific; cache per user.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),

      // --- Feature eligibility ----------------------------------------------
      'boost_eligible' => new StateDefinition(
        id: 'boost_eligible',
        category: MelStateContractCategory::FeatureEligibility,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        sourceSystems: ['boost', 'drupal_node'],
        interpretationRuleSummary: 'Fact feature.eligibility.boost from boost-owning services.',
        requiredPositiveSignals: ['feature.eligibility.boost'],
        blockingSignals: [],
        severity: MelStateSeverity::Low,
        uxImplications: 'Unlock boost prompts after lifecycle + commerce readiness.',
        ctaImplications: 'Boost CTA hidden until Satisfied.',
        accessibilityNotes: 'Describe benefit succinctly.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'analytics_eligible' => new StateDefinition(
        id: 'analytics_eligible',
        category: MelStateContractCategory::FeatureEligibility,
        surfaceOwnership: [MelSurfaceId::Vendor->value, MelSurfaceId::Staff->value],
        sourceSystems: ['analytics'],
        interpretationRuleSummary: 'Fact feature.eligibility.analytics.',
        requiredPositiveSignals: ['feature.eligibility.analytics'],
        blockingSignals: [],
        severity: MelStateSeverity::Low,
        uxImplications: 'Gated analytics frames interpret empty vs locked.',
        ctaImplications: 'Upsell upgrade when Unsatisfied.',
        accessibilityNotes: 'Provide text alternatives for charts.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'export_eligible' => new StateDefinition(
        id: 'export_eligible',
        category: MelStateContractCategory::FeatureEligibility,
        surfaceOwnership: [MelSurfaceId::Vendor->value, MelSurfaceId::Staff->value],
        sourceSystems: ['export', 'permissions'],
        interpretationRuleSummary: 'Fact feature.eligibility.export; still requires Drupal permissions.',
        requiredPositiveSignals: ['feature.eligibility.export'],
        blockingSignals: [],
        severity: MelStateSeverity::Medium,
        uxImplications: 'Export panels show eligibility messaging only.',
        ctaImplications: 'Export CTA requires permission plus Satisfied.',
        accessibilityNotes: 'Announce export readiness in status regions.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'featured_eligible' => new StateDefinition(
        id: 'featured_eligible',
        category: MelStateContractCategory::FeatureEligibility,
        surfaceOwnership: [MelSurfaceId::Vendor->value, MelSurfaceId::Staff->value],
        sourceSystems: ['discovery', 'drupal_node'],
        interpretationRuleSummary: 'Fact feature.eligibility.featured.',
        requiredPositiveSignals: ['feature.eligibility.featured'],
        blockingSignals: [],
        severity: MelStateSeverity::Low,
        uxImplications: 'Editorial placement prompts.',
        ctaImplications: 'Apply/request featured CTAs gated.',
        accessibilityNotes: 'Avoid hype-only wording.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'calendar_sync_eligible' => new StateDefinition(
        id: 'calendar_sync_eligible',
        category: MelStateContractCategory::FeatureEligibility,
        surfaceOwnership: [MelSurfaceId::Customer->value],
        sourceSystems: ['rsvp', 'commerce_order'],
        interpretationRuleSummary: 'Fact feature.eligibility.calendar_sync.',
        requiredPositiveSignals: ['feature.eligibility.calendar_sync'],
        blockingSignals: [],
        severity: MelStateSeverity::Low,
        uxImplications: 'Customer shell calendar prompts.',
        ctaImplications: 'Calendar download CTAs align with workflow.',
        accessibilityNotes: 'Link text names calendar format.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
      'vendor_upgrade_eligible' => new StateDefinition(
        id: 'vendor_upgrade_eligible',
        category: MelStateContractCategory::FeatureEligibility,
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        sourceSystems: ['billing', 'permissions'],
        interpretationRuleSummary: 'Fact feature.eligibility.vendor_upgrade.',
        requiredPositiveSignals: ['feature.eligibility.vendor_upgrade'],
        blockingSignals: [],
        severity: MelStateSeverity::Medium,
        uxImplications: 'Upgrade prompts without blocking core operations.',
        ctaImplications: 'Upgrade CTA secondary unless eligibility urgent.',
        accessibilityNotes: 'Summarise plan differences textually.',
        requiresAuthentication: TRUE,
        publicSafe: FALSE,
      ),
    ];
  }

  /**
   * @return array<string, \Drupal\myeventlane_surface\StateDefinition>
   */
  public function byCategory(MelStateContractCategory $category): array {
    return array_filter(
      $this->all(),
      static fn (StateDefinition $definition): bool => $definition->category === $category,
    );
  }

}
