<?php

declare(strict_types=1);

namespace Drupal\myeventlane_surface;

use Drupal\myeventlane_core\MelSurfaceId;

/**
 * Central catalogue of MEL workflow contracts (behavioural orchestration).
 */
final class MelWorkflowRegistry {

  /**
   * @return array<string, \Drupal\myeventlane_surface\WorkflowDefinition>
   */
  public function all(): array {
    return [
      // --- Customer ------------------------------------------------------------
      'account_created' => new WorkflowDefinition(
        id: 'account_created',
        domain: 'customer',
        surfaceOwnership: [MelSurfaceId::Auth->value],
        requiredSignals: [],
        completionSignals: [],
        nextStepRecommendations: ['first_login', 'profile_completed'],
        ctaPriority: 88,
        accessibilityNotes: 'Announce account creation success as a status region; focus moves to confirmation content.',
        activationExactRoutes: ['user.register'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'first_login' => new WorkflowDefinition(
        id: 'first_login',
        domain: 'customer',
        surfaceOwnership: [MelSurfaceId::Auth->value],
        requiredSignals: [],
        completionSignals: [],
        nextStepRecommendations: ['profile_completed', 'first_rsvp'],
        ctaPriority: 70,
        accessibilityNotes: 'Keep login errors programmatically determinable; success redirects remain primary flow.',
        activationExactRoutes: ['user.login'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'first_rsvp' => new WorkflowDefinition(
        id: 'first_rsvp',
        domain: 'customer',
        surfaceOwnership: [MelSurfaceId::Public->value, MelSurfaceId::Customer->value],
        requiredSignals: [],
        completionSignals: ['route.rsvp_thankyou'],
        nextStepRecommendations: ['calendar_connected', 'first_ticket_purchase'],
        ctaPriority: 62,
        accessibilityNotes: 'RSVP confirmation should use polite live regions; avoid stacking multiple primary CTAs.',
        activationRoutePrefixes: ['myeventlane_rsvp.'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'first_ticket_purchase' => new WorkflowDefinition(
        id: 'first_ticket_purchase',
        domain: 'customer',
        surfaceOwnership: [MelSurfaceId::Customer->value, MelSurfaceId::Public->value],
        requiredSignals: ['route.checkout_sensitive'],
        completionSignals: ['customer.flags.has_orders', 'route.order_detail'],
        nextStepRecommendations: ['calendar_prompt', 'social_share_prompt'],
        ctaPriority: 84,
        accessibilityNotes: 'Checkout stays distraction-minimal; post-purchase reassurance belongs on order detail.',
        activationRoutePrefixes: ['commerce_checkout'],
        activationPathPrefixes: ['/checkout', '/cart'],
        completionExactRoutes: ['myeventlane_checkout_flow.order_detail'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'first_saved_event' => new WorkflowDefinition(
        id: 'first_saved_event',
        domain: 'customer',
        surfaceOwnership: [MelSurfaceId::Customer->value],
        requiredSignals: [],
        completionSignals: [],
        nextStepRecommendations: ['first_ticket_purchase'],
        ctaPriority: 40,
        accessibilityNotes: 'Use clear heading hierarchy for saved lists; empty states describe next save action.',
        activationExactRoutes: ['myeventlane_dashboard.customer'],
        activationPathPrefixes: ['/my-events'],
        primaryCtaRouteName: 'myeventlane_dashboard.customer',
        primaryCtaTitle: 'Browse events',
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'calendar_connected' => new WorkflowDefinition(
        id: 'calendar_connected',
        domain: 'customer',
        surfaceOwnership: [MelSurfaceId::Customer->value],
        requiredSignals: [],
        completionSignals: ['customer.flags.calendar_connected'],
        nextStepRecommendations: ['social_share_prompt'],
        ctaPriority: 35,
        accessibilityNotes: 'Calendar exports should announce downloadable resource with descriptive link text.',
        activationExactRoutes: ['myeventlane_rsvp.ics_bundle'],
        activationPathPrefixes: ['/my-profile/download-rsvps.ics'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'profile_completed' => new WorkflowDefinition(
        id: 'profile_completed',
        domain: 'customer',
        surfaceOwnership: [MelSurfaceId::Customer->value],
        requiredSignals: [],
        completionSignals: ['customer.profile.complete'],
        nextStepRecommendations: ['first_saved_event', 'first_ticket_purchase'],
        ctaPriority: 72,
        accessibilityNotes: 'Profile forms already governed by MELFormSystem; progression messaging must not replace errors.',
        activationExactRoutes: ['myeventlane_account.settings'],
        primaryCtaRouteName: 'myeventlane_dashboard.customer',
        primaryCtaTitle: 'Discover events',
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),

      // --- Vendor --------------------------------------------------------------
      'vendor_account_created' => new WorkflowDefinition(
        id: 'vendor_account_created',
        domain: 'vendor',
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        requiredSignals: [],
        completionSignals: ['vendor.flags.has_vendor'],
        nextStepRecommendations: ['vendor_profile_completed'],
        ctaPriority: 60,
        accessibilityNotes: 'Vendor onboarding steps must remain keyboard reachable with labelled landmarks.',
        activationPathPrefixes: ['/vendor/onboard/account'],
        delegateVendorNextStepToOnboardingManager: TRUE,
      ),
      'vendor_profile_completed' => new WorkflowDefinition(
        id: 'vendor_profile_completed',
        domain: 'vendor',
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        requiredSignals: ['vendor.guidance.needs_resume'],
        completionSignals: ['vendor.onboarding.invite_ready'],
        nextStepRecommendations: ['stripe_connected', 'first_event_created'],
        ctaPriority: 75,
        accessibilityNotes: 'Do not duplicate field validation messaging from forms.',
        activationPathPrefixes: ['/vendor/onboard/profile', '/vendor/onboard/branding'],
        delegateVendorNextStepToOnboardingManager: TRUE,
      ),
      'stripe_connected' => new WorkflowDefinition(
        id: 'stripe_connected',
        domain: 'vendor',
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        requiredSignals: ['vendor.guidance.needs_resume'],
        completionSignals: ['vendor.flags.stripe_connected'],
        nextStepRecommendations: ['first_event_published', 'first_ticket_sold'],
        ctaPriority: 95,
        accessibilityNotes: 'Treat Stripe messaging as operational status, not promotional urgency.',
        activationPathPrefixes: ['/vendor/onboard/stripe', '/stripe/connect'],
        primaryCtaRouteName: 'myeventlane_vendor.onboard.stripe',
        primaryCtaTitle: 'Connect Stripe',
        delegateVendorNextStepToOnboardingManager: TRUE,
      ),
      'first_event_created' => new WorkflowDefinition(
        id: 'first_event_created',
        domain: 'vendor',
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        requiredSignals: ['vendor.guidance.needs_resume'],
        completionSignals: ['vendor.flags.has_events'],
        nextStepRecommendations: ['first_event_published'],
        ctaPriority: 80,
        accessibilityNotes: 'Event Studio remains authoritative for drafting; surface layer only guides.',
        activationPathPrefixes: ['/vendor/onboard/first-event'],
        activationRoutePrefixes: ['myeventlane_event_studio.'],
        delegateVendorNextStepToOnboardingManager: TRUE,
      ),
      'first_event_published' => new WorkflowDefinition(
        id: 'first_event_published',
        domain: 'vendor',
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        requiredSignals: [],
        completionSignals: [],
        nextStepRecommendations: ['first_ticket_sold', 'boost_offer_presented'],
        ctaPriority: 78,
        accessibilityNotes: 'Publishing guidance must not bypass moderation or access checks.',
        activationPathPrefixes: ['/vendor/events'],
        activationRequireAllSignals: ['vendor.guidance.needs_resume'],
        delegateVendorNextStepToOnboardingManager: TRUE,
      ),
      'first_ticket_sold' => new WorkflowDefinition(
        id: 'first_ticket_sold',
        domain: 'vendor',
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        requiredSignals: [],
        completionSignals: ['vendor.flags.has_tickets'],
        nextStepRecommendations: ['attendees_managed'],
        ctaPriority: 74,
        accessibilityNotes: 'Revenue milestones should reinforce trust without exposing purchaser PII.',
        activationRequireAllSignals: ['vendor.guidance.needs_resume', 'vendor.surface.active'],
        delegateVendorNextStepToOnboardingManager: TRUE,
      ),
      'attendees_managed' => new WorkflowDefinition(
        id: 'attendees_managed',
        domain: 'vendor',
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        requiredSignals: [],
        completionSignals: [],
        nextStepRecommendations: ['boost_offer_presented'],
        ctaPriority: 45,
        accessibilityNotes: 'Check-in interfaces must maintain per-event access boundaries.',
        activationRoutePrefixes: ['myeventlane_rsvp.vendor_', 'myeventlane_checkout_flow.vendor_'],
        activationPathPrefixes: ['/vendor/events'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'boost_offer_presented' => new WorkflowDefinition(
        id: 'boost_offer_presented',
        domain: 'vendor',
        surfaceOwnership: [MelSurfaceId::Vendor->value],
        requiredSignals: [],
        completionSignals: [],
        nextStepRecommendations: [],
        ctaPriority: 55,
        accessibilityNotes: 'Boost messaging remains secondary to operational readiness CTAs.',
        activationExactRoutes: ['myeventlane_vendor.onboard.boost'],
        activationPathPrefixes: ['/vendor/onboard/boost'],
        delegateVendorNextStepToOnboardingManager: TRUE,
      ),

      // --- Checkout ------------------------------------------------------------
      'ticket_selected' => new WorkflowDefinition(
        id: 'ticket_selected',
        domain: 'checkout',
        surfaceOwnership: [MelSurfaceId::Public->value, MelSurfaceId::Customer->value],
        requiredSignals: ['route.checkout_sensitive'],
        completionSignals: [],
        nextStepRecommendations: ['attendee_info_complete'],
        ctaPriority: 50,
        accessibilityNotes: 'Cart summaries must remain readable when zoomed to 200%.',
        activationRoutePrefixes: ['commerce_cart'],
        activationPathPrefixes: ['/cart'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'attendee_info_complete' => new WorkflowDefinition(
        id: 'attendee_info_complete',
        domain: 'checkout',
        surfaceOwnership: [MelSurfaceId::Public->value, MelSurfaceId::Customer->value],
        requiredSignals: ['route.commerce_checkout'],
        completionSignals: [],
        nextStepRecommendations: ['checkout_started'],
        ctaPriority: 52,
        accessibilityNotes: 'Inline validation belongs to Commerce panes; surface layer never replaces errors.',
        activationRoutePrefixes: ['commerce_checkout'],
        activationPathPrefixes: ['/checkout'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'checkout_started' => new WorkflowDefinition(
        id: 'checkout_started',
        domain: 'checkout',
        surfaceOwnership: [MelSurfaceId::Public->value, MelSurfaceId::Customer->value],
        requiredSignals: ['route.commerce_checkout'],
        completionSignals: [],
        nextStepRecommendations: ['payment_complete'],
        ctaPriority: 48,
        accessibilityNotes: 'Avoid promotional bands inside checkout; reassurance only.',
        activationRoutePrefixes: ['commerce_checkout'],
        activationPathPrefixes: ['/checkout'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'payment_complete' => new WorkflowDefinition(
        id: 'payment_complete',
        domain: 'checkout',
        surfaceOwnership: [MelSurfaceId::Public->value, MelSurfaceId::Customer->value],
        requiredSignals: ['route.commerce_checkout'],
        completionSignals: [],
        nextStepRecommendations: ['order_confirmed'],
        ctaPriority: 90,
        accessibilityNotes: 'Payment success should use polite status semantics until navigation settles.',
        activationRoutePrefixes: ['commerce_checkout'],
        activationPathPrefixes: ['/checkout'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'order_confirmed' => new WorkflowDefinition(
        id: 'order_confirmed',
        domain: 'checkout',
        surfaceOwnership: [MelSurfaceId::Customer->value],
        requiredSignals: [],
        completionSignals: ['route.order_detail'],
        nextStepRecommendations: ['calendar_prompt', 'social_share_prompt'],
        ctaPriority: 92,
        accessibilityNotes: 'Confirmation summaries must not leak privileged attendee data across accounts.',
        activationExactRoutes: ['myeventlane_checkout_flow.order_detail'],
        completionExactRoutes: ['myeventlane_checkout_flow.order_detail'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'calendar_prompt' => new WorkflowDefinition(
        id: 'calendar_prompt',
        domain: 'checkout',
        surfaceOwnership: [MelSurfaceId::Customer->value],
        requiredSignals: ['route.order_detail'],
        completionSignals: ['customer.flags.calendar_connected'],
        nextStepRecommendations: ['social_share_prompt'],
        ctaPriority: 42,
        accessibilityNotes: 'Offer calendar actions as secondary to ticket access.',
        activationExactRoutes: ['myeventlane_checkout_flow.order_detail'],
        primaryCtaRouteName: 'myeventlane_rsvp.ics_bundle',
        primaryCtaTitle: 'Add to calendar',
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'social_share_prompt' => new WorkflowDefinition(
        id: 'social_share_prompt',
        domain: 'checkout',
        surfaceOwnership: [MelSurfaceId::Customer->value],
        requiredSignals: ['route.order_detail'],
        completionSignals: [],
        nextStepRecommendations: ['first_saved_event'],
        ctaPriority: 25,
        accessibilityNotes: 'Social prompts must not autoplay media or trap focus.',
        activationExactRoutes: ['myeventlane_checkout_flow.order_detail'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),

      // --- Support -------------------------------------------------------------
      'support_contact_started' => new WorkflowDefinition(
        id: 'support_contact_started',
        domain: 'support',
        surfaceOwnership: [
          MelSurfaceId::Public->value,
          MelSurfaceId::Customer->value,
          MelSurfaceId::Vendor->value,
        ],
        requiredSignals: [],
        completionSignals: [],
        nextStepRecommendations: ['issue_resolved'],
        ctaPriority: 30,
        accessibilityNotes: 'Help landmarks must be labelled; search results need readable headings.',
        activationPathPrefixes: ['/help'],
        activationRoutePrefixes: ['myeventlane_help_centre.'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'refund_request_started' => new WorkflowDefinition(
        id: 'refund_request_started',
        domain: 'support',
        surfaceOwnership: [MelSurfaceId::Customer->value, MelSurfaceId::Vendor->value],
        requiredSignals: [],
        completionSignals: [],
        nextStepRecommendations: ['issue_resolved'],
        ctaPriority: 85,
        accessibilityNotes: 'Refund flows inherit Commerce permissions; never expose other buyers’ orders.',
        activationRoutePrefixes: ['myeventlane_refunds.'],
        activationPathPrefixes: ['/my-tickets/order'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'escalation_detected' => new WorkflowDefinition(
        id: 'escalation_detected',
        domain: 'support',
        surfaceOwnership: [MelSurfaceId::Staff->value, MelSurfaceId::Vendor->value],
        requiredSignals: ['support.flags.escalation'],
        completionSignals: [],
        nextStepRecommendations: ['issue_resolved'],
        ctaPriority: 94,
        accessibilityNotes: 'Escalation banners must be alerts only when severity demands assertive delivery.',
        activationRequireAllSignals: ['support.flags.escalation'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
      'issue_resolved' => new WorkflowDefinition(
        id: 'issue_resolved',
        domain: 'support',
        surfaceOwnership: [
          MelSurfaceId::Public->value,
          MelSurfaceId::Customer->value,
          MelSurfaceId::Vendor->value,
          MelSurfaceId::Staff->value,
        ],
        requiredSignals: [],
        completionSignals: ['support.flags.resolved'],
        nextStepRecommendations: [],
        ctaPriority: 20,
        accessibilityNotes: 'Closure messaging should reaffirm next trusted actions without stacking CTAs.',
        activationRequireAllSignals: ['support.flags.resolved'],
        delegateVendorNextStepToOnboardingManager: FALSE,
      ),
    ];
  }

}
