<?php

/**
 * @file
 */

declare(strict_types=1);

/**
 * @file
 * MyEventLane RSVP module hooks.
 */

/**
 * Implements hook_theme().
 */
function myeventlane_rsvp_theme($existing, $type, $theme, $path): array {
  return [
    'mel_rsvp_thankyou' => [
      'variables' => [
        'title' => NULL,
        'message' => NULL,
        'event_title' => NULL,
        'event_link' => NULL,
        'donation_enabled' => FALSE,
      ],
      // Provide a default template shipped by the module.
      'template' => 'mel-rsvp-thankyou',
      'path' => $path . '/templates',
    ],
  ];
}
