<?php

declare(strict_types=1);

namespace Drupal\myeventlane_core\Commands;

use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\myeventlane_core\PlatformFeeDefaults;
use Drush\Commands\DrushCommands;

/**
 * Core MyEventLane Drush commands (environment sanity).
 */
final class MelCoreCommands extends DrushCommands {

  private const RELEASE_METADATA_FILE = 'build/release-metadata.json';

  public function __construct(
    private readonly ConfigFactoryInterface $configFactory,
    private readonly string $appRoot,
  ) {
    parent::__construct();
  }

  /**
   * Validates active config for DDEV leakage, platform fee range, and domain/env alignment.
   *
   * @command mel:healthcheck
   * @usage drush mel:healthcheck
   *   Run MyEventLane environment sanity checks (read-only except exit code).
   *
   * @return int
   *   0 if OK, 1 if failures.
   */
  public function healthcheck(): int {
    $failures = 0;
    $isDdev = getenv('IS_DDEV_PROJECT') === 'true';

    $domainCfg = $this->configFactory->get('myeventlane_core.domain_settings');
    foreach (['public_domain', 'vendor_domain', 'admin_domain'] as $key) {
      $val = (string) $domainCfg->get($key);
      if ($val !== '' && str_contains(strtolower($val), 'ddev.site') && !$isDdev) {
        $this->io()->error("Active config {$key} references ddev.site outside DDEV: {$val}");
        $failures++;
      }
    }

    $feeRaw = $this->configFactory->get('myeventlane_core.settings')->get('platform_fee_percent');
    $fee = PlatformFeeDefaults::normalizePercent($feeRaw);
    $this->io()->writeln(sprintf('platform_fee_percent (normalized): %s', $fee));

    $appEnv = strtolower((string) (getenv('APP_ENV') ?: ''));

    if (in_array($appEnv, ['production', 'prod'], TRUE)) {
      $expect = [
        'public_domain' => 'https://myeventlane.com.au',
        'vendor_domain' => 'https://vendor.myeventlane.com.au',
        'admin_domain' => 'https://admin.myeventlane.com.au',
      ];
      foreach ($expect as $k => $expected) {
        $actual = (string) $domainCfg->get($k);
        if ($actual !== $expected) {
          $this->io()->error("APP_ENV=production expects {$k}={$expected}, got {$actual}.");
          $failures++;
        }
      }
    }
    elseif (in_array($appEnv, ['staging', 'stage'], TRUE)) {
      $expect = [
        'public_domain' => 'https://staging.myeventlane.com.au',
        'vendor_domain' => 'https://vendor.staging.myeventlane.com.au',
        'admin_domain' => 'https://admin.staging.myeventlane.com.au',
      ];
      foreach ($expect as $k => $expected) {
        $actual = (string) $domainCfg->get($k);
        if ($actual !== $expected) {
          $this->io()->error("APP_ENV=staging expects {$k}={$expected}, got {$actual}.");
          $failures++;
        }
      }
    }
    else {
      $this->io()->note('APP_ENV not set to production|staging — skipping strict domain trio assertion.');
    }

    if ($failures > 0) {
      $this->io()->error("mel:healthcheck failed with {$failures} error(s).");
      return 1;
    }

    $this->io()->success('mel:healthcheck passed.');
    return 0;
  }

  /**
   * Displays release metadata generated by the validation workflow.
   *
   * @command mel:build-info
   * @usage drush mel:build-info
   *   Show read-only release metadata from build/release-metadata.json.
   *
   * @return int
   *   0 if metadata was displayed, 1 if metadata is missing or unreadable.
   */
  public function buildInfo(): int {
    $metadataPath = dirname($this->appRoot) . DIRECTORY_SEPARATOR . self::RELEASE_METADATA_FILE;

    if (!is_readable($metadataPath)) {
      $this->io()->warning(sprintf('Release metadata not found or unreadable: %s', self::RELEASE_METADATA_FILE));
      $this->io()->writeln('Run the release validator successfully to generate metadata.');
      return 1;
    }

    $contents = file_get_contents($metadataPath);
    if ($contents === FALSE) {
      $this->io()->error(sprintf('Unable to read release metadata: %s', self::RELEASE_METADATA_FILE));
      return 1;
    }

    try {
      $metadata = json_decode($contents, TRUE, 512, JSON_THROW_ON_ERROR);
    }
    catch (\JsonException $e) {
      $this->io()->error(sprintf('Release metadata is not valid JSON: %s', $e->getMessage()));
      return 1;
    }

    if (!is_array($metadata)) {
      $this->io()->error('Release metadata JSON must contain an object.');
      return 1;
    }

    $this->io()->title('MyEventLane build information');
    $this->io()->table(
      ['Field', 'Value'],
      [
        ['Validator version', $this->metadataValue($metadata, 'validator_version')],
        ['Validation target', $this->metadataValue($metadata, 'target')],
        ['Validated at', $this->metadataValue($metadata, 'validated_at_utc')],
        ['Drupal version', $this->metadataValue($metadata, 'drupal_version')],
        ['PHP version', $this->metadataValue($metadata, 'php_version')],
        ['Drush version', $this->metadataValue($metadata, 'drush_version')],
        ['Site URI', $this->metadataValue($metadata, 'site_uri')],
        ['Branch', $this->metadataValue($metadata, 'branch')],
        ['Commit', $this->metadataValue($metadata, 'commit')],
        ['Commit message', $this->metadataValue($metadata, 'commit_message')],
        ['Remote tracking branch', $this->metadataValue($metadata, 'remote_tracking_branch')],
        ['Ahead / behind', sprintf('%s / %s', $this->metadataValue($metadata, 'ahead'), $this->metadataValue($metadata, 'behind'))],
        ['Drupal status', $this->metadataValue($metadata, 'drupal_status')],
        ['Database status', $this->metadataValue($metadata, 'database_status')],
        ['Configuration status', $this->metadataValue($metadata, 'config_status')],
        ['Governance status', $this->metadataValue($metadata, 'governance_status')],
        ['Tests status', $this->metadataValue($metadata, 'tests_status')],
        ['Build status', $this->metadataValue($metadata, 'build_status')],
      ]
    );

    return 0;
  }

  /**
   * Returns a display-safe metadata value.
   *
   * @param array<string, mixed> $metadata
   *   Release metadata decoded from build/release-metadata.json.
   * @param string $key
   *   Metadata key.
   */
  private function metadataValue(array $metadata, string $key): string {
    if (!array_key_exists($key, $metadata) || $metadata[$key] === NULL || $metadata[$key] === '') {
      return 'Not recorded';
    }

    if (is_bool($metadata[$key])) {
      return $metadata[$key] ? 'true' : 'false';
    }

    if (is_scalar($metadata[$key])) {
      return (string) $metadata[$key];
    }

    return 'Not recorded';
  }

}
