<?php

declare(strict_types=1);

namespace Drupal\myeventlane_core;

/**
 * Canonical schema for release metadata generated by MEL validation.
 */
final class ReleaseMetadataSchema {

  public const FILE = 'build/release-metadata.json';

  private const TYPE_INT = 'int';
  private const TYPE_STRING = 'string';

  /**
   * Metadata fields in canonical write and display order.
   *
   * @var array<string, array{label: string, type: string}>
   */
  private const FIELDS = [
    'validator_version' => [
      'label' => 'Validator version',
      'type' => self::TYPE_STRING,
    ],
    'target' => [
      'label' => 'Validation target',
      'type' => self::TYPE_STRING,
    ],
    'branch' => [
      'label' => 'Branch',
      'type' => self::TYPE_STRING,
    ],
    'commit' => [
      'label' => 'Commit',
      'type' => self::TYPE_STRING,
    ],
    'commit_message' => [
      'label' => 'Commit message',
      'type' => self::TYPE_STRING,
    ],
    'remote_tracking_branch' => [
      'label' => 'Remote tracking branch',
      'type' => self::TYPE_STRING,
    ],
    'ahead' => [
      'label' => 'Ahead',
      'type' => self::TYPE_INT,
    ],
    'behind' => [
      'label' => 'Behind',
      'type' => self::TYPE_INT,
    ],
    'validated_at_utc' => [
      'label' => 'Validated at',
      'type' => self::TYPE_STRING,
    ],
    'drupal_version' => [
      'label' => 'Drupal version',
      'type' => self::TYPE_STRING,
    ],
    'php_version' => [
      'label' => 'PHP version',
      'type' => self::TYPE_STRING,
    ],
    'drush_version' => [
      'label' => 'Drush version',
      'type' => self::TYPE_STRING,
    ],
    'site_uri' => [
      'label' => 'Site URI',
      'type' => self::TYPE_STRING,
    ],
    'drupal_status' => [
      'label' => 'Drupal status',
      'type' => self::TYPE_STRING,
    ],
    'database_status' => [
      'label' => 'Database status',
      'type' => self::TYPE_STRING,
    ],
    'config_status' => [
      'label' => 'Configuration status',
      'type' => self::TYPE_STRING,
    ],
    'governance_status' => [
      'label' => 'Governance status',
      'type' => self::TYPE_STRING,
    ],
    'tests_status' => [
      'label' => 'Tests status',
      'type' => self::TYPE_STRING,
    ],
    'build_status' => [
      'label' => 'Build status',
      'type' => self::TYPE_STRING,
    ],
  ];

  /**
   * Builds metadata from values passed in canonical field order.
   *
   * @param list<string> $values
   *   Raw metadata values in the order defined by self::FIELDS.
   *
   * @return array<string, int|string|null>
   *   Normalised release metadata.
   */
  public static function createFromOrderedValues(array $values): array {
    $metadata = [];
    $index = 0;

    foreach (self::FIELDS as $key => $definition) {
      $value = $values[$index] ?? '';
      $metadata[$key] = self::normaliseValue($value, $definition['type']);
      $index++;
    }

    return $metadata;
  }

  /**
   * Builds display rows for every canonical metadata field.
   *
   * @param array<string, mixed> $metadata
   *   Release metadata decoded from build/release-metadata.json.
   *
   * @return list<array{0: string, 1: string}>
   *   Rows suitable for Drush table output.
   */
  public static function displayRows(array $metadata): array {
    $rows = [];

    foreach (self::FIELDS as $key => $definition) {
      $rows[] = [
        $definition['label'],
        self::displayValue($metadata[$key] ?? NULL),
      ];
    }

    return $rows;
  }

  /**
   * Returns a display-safe metadata value.
   */
  private static function displayValue(mixed $value): string {
    if ($value === NULL || $value === '') {
      return 'Not recorded';
    }

    if (is_bool($value)) {
      return $value ? 'true' : 'false';
    }

    if (is_scalar($value)) {
      return (string) $value;
    }

    return 'Not recorded';
  }

  /**
   * Normalises raw validator values before JSON encoding.
   */
  private static function normaliseValue(string $value, string $type): int|string|null {
    if ($value === '') {
      return NULL;
    }

    if ($type === self::TYPE_INT) {
      return (int) $value;
    }

    return $value;
  }

}
