<?php

declare(strict_types=1);

namespace Drupal\myeventlane_vendor_ai\Form;

use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\myeventlane_ai\Service\AiJobEnqueueService;
use Drupal\myeventlane_escalations_portal\Service\EscalationPartyResolver;
use Drupal\myeventlane_help_shared\Service\UnifiedHelpRetriever;
use Drupal\myeventlane_vendor_ai\Service\VendorAiContextBuilder;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;

/**
 * Form for vendor AI assistant question.
 *
 * On submit: creates ai_job, enqueues; async worker executes.
 * Frontend polls for result.
 *
 * IMPORTANT: Escalation ID is taken from route parameter only.
 */
final class VendorAiAssistantForm extends FormBase {

  public function __construct(
    private readonly AiJobEnqueueService $jobEnqueue,
    private readonly VendorAiContextBuilder $contextBuilder,
    private readonly UnifiedHelpRetriever $unifiedHelpRetriever,
    private readonly EntityTypeManagerInterface $entityTypeManager,
    private readonly EscalationPartyResolver $partyResolver,
  ) {}

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container): self {
    return new self(
      $container->get('myeventlane_ai.job_enqueue'),
      $container->get('myeventlane_vendor_ai.context_builder'),
      $container->get('myeventlane_help_shared.unified_help_retriever'),
      $container->get('entity_type.manager'),
      $container->get('myeventlane_escalations_portal.party_resolver'),
    );
  }

  /**
   * {@inheritdoc}
   */
  public function getFormId(): string {
    return 'myeventlane_vendor_ai_assistant_form';
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state, ?int $escalation_id = NULL): array {
    $form_state->disableCache();

    $escalation_id = $escalation_id ?? (int) $form_state->get('escalation_id');
    if ($escalation_id <= 0) {
      throw new AccessDeniedHttpException();
    }
    $form_state->set('escalation_id', $escalation_id);

    $form['question'] = [
      '#type' => 'textarea',
      '#title' => $this->t('Your question'),
      '#required' => TRUE,
      '#rows' => 3,
      '#attributes' => [
        'placeholder' => $this->t('e.g. What is the refund policy for cancelled events?'),
      ],
    ];

    $form['actions'] = [
      '#type' => 'actions',
    ];
    $form['actions']['submit'] = [
      '#type' => 'submit',
      '#value' => $this->t('Ask MEL Assistant'),
      '#attributes' => ['class' => ['button', 'button--primary']],
    ];

    $job_id = $form_state->get('ai_job_id');
    if ($job_id) {
      $form['result'] = [
        '#type' => 'container',
        '#attributes' => ['class' => ['mel-ai-panel', 'mel-ai-panel__result']],
        '#weight' => 100,
      ];
      $form['result']['disclosure'] = [
        '#type' => 'container',
        '#attributes' => ['class' => ['mel-ai-panel__disclosure']],
        '#weight' => -10,
        'text' => [
          '#plain_text' => (string) $this->t('This response is generated by an AI assistant. It may contain errors and does not replace formal support advice.'),
        ],
      ];
      $form['result']['generating'] = [
        '#type' => 'container',
        '#attributes' => [
          'class' => ['mel-ai-panel__generating'],
          'data-job-id' => (string) $job_id,
          'data-poll-url' => Url::fromRoute('myeventlane_ai.job_poll', ['ai_job' => $job_id])->toString(),
        ],
        'text' => [
          '#markup' => '<p>' . $this->t('Generating…') . '</p>',
        ],
      ];
      $form['result']['answer'] = [
        '#type' => 'container',
        '#attributes' => ['class' => ['mel-ai-panel__answer'], 'hidden' => 'true', 'aria-hidden' => 'true'],
      ];
      $articles = $form_state->get('ai_articles') ?? [];
      $items = [];
      foreach ($articles as $art) {
        $raw_url = trim((string) ($art['url'] ?? ''));
        if ($raw_url === '') continue;
        try {
          if (str_starts_with($raw_url, '/')) {
            $url = Url::fromUserInput($raw_url);
          } elseif (preg_match('#^https?://#', $raw_url)) {
            $url = Url::fromUri($raw_url);
          } else {
            continue;
          }
          $items[] = [
            '#type' => 'link',
            '#title' => $art['title'] ?? '',
            '#url' => $url,
          ];
        } catch (\Exception $e) {
          continue;
        }
      }
      $form['result']['articles'] = [
        '#theme' => 'item_list',
        '#title' => $this->t('Relevant articles'),
        '#items' => $items,
      ];
      $form['#attached']['library'][] = 'myeventlane_ai/ai_poll';
    }

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function validateForm(array &$form, FormStateInterface $form_state): void {
    $question = trim((string) $form_state->getValue('question'));
    if (mb_strlen($question) < 10) {
      $form_state->setErrorByName('question', $this->t('Please enter at least 10 characters.'));
    }
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state): void {
    $question = trim((string) $form_state->getValue('question'));

    $escalation_id = (int) $form_state->get('escalation_id');
    if ($escalation_id <= 0) {
      throw new AccessDeniedHttpException();
    }

    $escalation = $this->entityTypeManager->getStorage('escalation')->load($escalation_id);
    if (!$escalation) {
      throw new AccessDeniedHttpException();
    }

    $account = $this->currentUser();
    if (!$this->partyResolver->isVendor($account, $escalation) && !$this->partyResolver->isStaff($account)) {
      throw new AccessDeniedHttpException();
    }

    $articles = $this->mapUnifiedRowsToVendorAiArticles(
      $this->unifiedHelpRetriever->retrieveForUser($question, $account, 5),
    );
    $context = $this->contextBuilder->build($escalation_id, $articles);

    if (isset($context['error'])) {
      $this->messenger()->addError($this->t('I could not load the escalation context. Please try again later.'));
      $form_state->setRebuild();
      return;
    }

    $form_state->set('ai_articles', $articles);

    $vendor_id = null;
    if ($escalation->hasField('vendor_id') && !$escalation->get('vendor_id')->isEmpty()) {
      $vendor_id = (int) $escalation->get('vendor_id')->target_id;
    }

    $excerpts = '';
    foreach ($context['help_excerpts'] ?? [] as $i => $art) {
      $excerpts .= "\n--- Article " . ($i + 1) . ": " . ($art['title'] ?? '') . " ---\n";
      $excerpts .= ($art['excerpt'] ?? '') . "\n";
    }

    $context_block = "Type={$context['type']}, Priority={$context['priority']}, "
      . "Status={$context['status']}, Waiting on={$context['waiting_on']}, SLA={$context['sla_label']}.";

    $placeholders = [
      'context_block' => $context_block,
      'excerpts' => $excerpts ?: ' (none)',
      'question' => $question,
    ];

    $job = $this->jobEnqueue->enqueue(
      'vendor_ai.answer',
      'v1',
      $placeholders,
      [],
      (int) $this->currentUser()->id(),
      'vendor_ai:escalation:' . $escalation_id,
      $vendor_id,
    );

    $form_state->set('ai_job_id', (int) $job->id());
    $form_state->setRebuild();
  }

  /**
   * Maps UnifiedHelpRetriever rows to the legacy HelpArticleRetriever shape.
   *
   * @param array<int, array<string, mixed>> $rows
   *
   * @return array<int, array{nid: int, title: string, url: string, excerpt: string}>
   */
  private function mapUnifiedRowsToVendorAiArticles(array $rows): array {
    $out = [];
    foreach ($rows as $row) {
      $plain = trim((string) ($row['content'] ?? $row['summary'] ?? ''));
      if ($plain === '') {
        $plain = trim((string) ($row['title'] ?? ''));
      }
      $excerpt = $plain;
      if (mb_strlen($excerpt) > 400) {
        $excerpt = mb_substr($excerpt, 0, 400) . '…';
      }
      $out[] = [
        'nid' => (int) ($row['nid'] ?? 0),
        'title' => (string) ($row['title'] ?? ''),
        'url' => (string) ($row['url'] ?? ''),
        'excerpt' => $excerpt,
      ];
    }
    return $out;
  }

}
